### ISSUE TITLE
Value cannot be null. Parameter name: httpContext

### ISSUE THREAD

**Issue by derigel23** [NuGet/NuGetGallery#1246]
```
System.ArgumentNullException
Value cannot be null. Parameter name: httpContext

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: httpContext
   at System.Web.HttpContextWrapper..ctor(HttpContext httpContext)
   at Glimpse.AspNet.AspNetFrameworkProvider.get_HttpRequestStore()
   at Glimpse.Core.Framework.Factory.<>c__DisplayClass2.<InstantiateTimerStrategy>b__1()
   at Glimpse.Core.TraceListener.InternalWrite(String message, String category)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at NuGetGallery.Infrastructure.Jobs.NuGetJobCoordinator.<>c__DisplayClass3.<GetWork>b__1(Task t) in c:\Projects\NuGetGallery\Website\Infrastructure\Jobs\NuGetJobCoordinator.cs:line 36
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at NuGetGallery.Infrastructure.Jobs.NuGetJobCoordinator.<>c__DisplayClass6.<CreateWrappingContinuingTask>b__5() in c:\Projects\NuGetGallery\Website\Infrastructure\Jobs\NuGetJobCoordinator.cs:line 50
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at WebBackgrounder.JobHost.DoWork(Task work)
   at WebBackgrounder.JobManager.DoNextJob()
   at WebBackgrounder.JobManager.OnTimerElapsed(Object sender)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: httpContext
   at System.Web.HttpContextWrapper..ctor(HttpContext httpContext)
   at Glimpse.AspNet.AspNetFrameworkProvider.get_HttpRequestStore()
   at Glimpse.Core.Framework.Factory.<>c__DisplayClass2.<InstantiateTimerStrategy>b__1()
   at Glimpse.Core.TraceListener.InternalWrite(String message, String category)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at NuGetGallery.Infrastructure.Jobs.NuGetJobCoordinator.<>c__DisplayClass3.<GetWork>b__1(Task t) in c:\Projects\NuGetGallery\Website\Infrastructure\Jobs\NuGetJobCoordinator.cs:line 36
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at NuGetGallery.Infrastructure.Jobs.NuGetJobCoordinator.<>c__DisplayClass6.<CreateWrappingContinuingTask>b__5() in c:\Projects\NuGetGallery\Website\Infrastructure\Jobs\NuGetJobCoordinator.cs:line 50
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: httpContext
   at System.Web.HttpContextWrapper..ctor(HttpContext httpContext)
   at Glimpse.AspNet.AspNetFrameworkProvider.get_HttpRequestStore()
   at Glimpse.Core.Framework.Factory.<>c__DisplayClass2.<InstantiateTimerStrategy>b__1()
   at Glimpse.Core.TraceListener.InternalWrite(String message, String category)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at NuGetGallery.Infrastructure.Jobs.NuGetJobCoordinator.<>c__DisplayClass3.<GetWork>b__1(Task t) in c:\Projects\NuGetGallery\Website\Infrastructure\Jobs\NuGetJobCoordinator.cs:line 36
   at System.Threading.Tasks.Task.Execute()<---
<---
```

**Comment by bipin24x7** [comment]
Do we have the fix for this? I am seeing below exception when saving content in thread which is running in background.

Parameter name: httpContext
System.ArgumentNullException: Value cannot be null.
Parameter name: httpContext
   at System.Web.HttpContextWrapper..ctor(HttpContext httpContext)
   at Umbraco.Web.SingletonHttpContextAccessor.get_Value()
   at Umbraco.Web.RequestLifespanMessagesFactory.Get()
   at Umbraco.Core.Services.ContentService.SaveAndPublishDo(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Core.Services.ContentService.Publish(IContent content, Int32 userId)
