### ISSUE TITLE
OData service - Call to the Search function returns malformed result

### ISSUE THREAD

**Issue by filyakov** [NuGet/NuGetGallery#1259]
Try to call it with the $top more than 40, for example:

http://packages.nuget.org/v1/FeedService.svc/Search?$top=41

Returned data misses 2 closing elements in both Atom and JSON formats and so parsing of this data fails.

The actual cause of this problem might be a System.NullReferenceException in OData service serializer:

at System.Data.Services.Serializers.DataStringEscapeBuilder.Build()
at System.Data.Services.Serializers.Serializer.GetNextPageQueryParametersForRootContainer()
at System.Data.Services.Serializers.Serializer.GetNextLinkUri(Object lastObject, IExpandedResult skipTokenExpandedResult, Uri absoluteUri)
at System.Data.Services.Serializers.SyndicationSerializer.WriteNextPageLink(Object lastElement, IExpandedResult expandedResult, Uri absoluteUri)
at System.Data.Services.Serializers.SyndicationSerializer.&lt;DeferredFeedItems&gt;d__b.MoveNext()
at System.ServiceModel.Syndication.Atom10FeedFormatter.WriteItems(XmlWriter writer, IEnumerable`1 items, Uri feedBaseUri)
at System.ServiceModel.Syndication.Atom10FeedFormatter.WriteFeedTo(XmlWriter writer, SyndicationFeed feed, Boolean isSourceFeed)
at System.ServiceModel.Syndication.Atom10FeedFormatter.WriteTo(XmlWriter writer)
at System.Data.Services.Serializers.Serializer.WriteRequest(IEnumerator queryResults, Boolean hasMoved)
at System.Data.Services.ResponseBodyWriter.Write(Stream stream)

**Comment by maartenba** [comment]
Relates to #1502, #1886 and #1259 - found out this is a bug in `System.Data.Services` (also described at https://social.msdn.microsoft.com/Forums/en-US/6cc0ef87-80ec-4331-8b41-efb22d8f1c60/odata-provider-with-wcf-40-paging-operations-with-null-parameters?forum=adodotnetdataservices).

Created a pull request with the OData folks - https://github.com/OData/odata.net/pull/149

**Comment by maartenba** [comment]
Fixed.
