### ISSUE TITLE
IE8:  WSOD on submitting anonymous abuse report

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1937]
1.  In IE8, go to a package page while not logged in, click "Report Abuse", and type up an abuse report using the form.
2.  Click Submit

Result:  Invariably, you will get a WSOD error page.  Investigating the ELMAH logs reveals that the issue is coming from Recaptcha.
Expected:  Oddly, this doesn't happen on more recent versions of IE.  In any case, we shouldn't be gating our use (or lack of use) of Recaptcha on a browser version.

Note:  The stack trace is the following:
System.InvalidOperationException: The default reCAPTCHA API keys may only be used for local requests. Configure your app's own API keys in app settings.
   at PoliteCaptcha.ReCaptchaValidator.Validate(HttpContextBase httpContext)
   at PoliteCaptcha.ValidateSpamPreventionAttribute.Authorize(HttpContextBase httpContext, ModelStateDictionary modelState, ICaptchaValidator captchaValidator)
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass25.<BeginInvokeAction>b__1e(AsyncCallback asyncCallback, Object asyncState)

**Comment by johnataylor** [comment]
This is the old gallery code on an old browser. Closing.
