### ISSUE TITLE
'Sequence contains more than one element' following simultaneous NuGet push

### ISSUE THREAD

**Issue by efergus** [NuGet/NuGetGallery#1959]
If a package with same ID is simultaneously pushed to the NuGet gallery server, and that package ID doesn't pre-exist, you can get duplicate PackageRegistration rows (and associated rows) for this package, even if a prerelease or different version is used on the package.  Later attempts to push new versions of this package will result in the following error & the only known solution is to manually cleanup the db entries.
```
System.InvalidOperationException: Failed to process request. 'Sequence contains more than one element'. 
[16:30:34][MSBuild output] EXEC : The remote server returned an error : (500) Internal Server Error.. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error. [C:\BuildAgent\work\ccb7ae74f291883\.build\Build.proj.teamcity]
[16:30:34][MSBuild output]      at System.Net.HttpWebRequest.GetResponse()
[16:30:34][MSBuild output]      at NuGet.RequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, IProxyCache proxyCache, ICredentialCache credentialCache, ICredentialProvider credentialProvider)
[16:30:34][MSBuild output]      at NuGet.HttpClient.GetResponse()
[16:30:34][MSBuild output]      at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
[16:30:34][MSBuild output]      --- End of inner exception stack trace ---
[16:30:34][MSBuild output]      at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
[16:30:34][MSBuild output]      at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int32 timeout)
[16:30:34][MSBuild output]      at NuGet.PackageServer.PushPackage(String apiKey, IPackage package, Int32 timeout)
[16:30:34][MSBuild output]      at NuGet.Commands.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packageToPush, TimeSpan timeout)
[16:30:34][MSBuild output]      at NuGet.Commands.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
[16:30:34][MSBuild output]      at NuGet.Commands.PushCommand.ExecuteCommand()
[16:30:34][MSBuild output]      at NuGet.Commands.Command.Execute()
[16:30:34][MSBuild output]      at NuGet.Program.Main(String[] args)
```

**Comment by johnataylor** [comment]
If this repo's on NuGet.org this is quite poor behavior and should be fixed. Even for v3 feed in RTM milestone we still use the same publish path through the gallery.

**Comment by maartenba** [comment]
Working on this in #2509
