### ISSUE TITLE
NullReferenceException in VS 2015 CTP6 in InstallPackages against local NuGet repo

### ISSUE THREAD

**Issue by rkeithhill** [NuGet/NuGetGallery#2374]
This is the error I see (below).  Our ASP.NET MVC web site is hosting NuGet.Server 2.8.3.  I do not see an update for this package.  Perhaps this is a mismatch between the 3.0 client and the server that will get fixed when someone drops an update for NuGet.Server?

```
Error occured:\nSystem.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.PackageManagement.UI.PackageLoader.<>c__DisplayClass1a.<<SearchInstalled>b__10>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<SearchInstalled>d__2a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<Search>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.PackageLoader.<LoadItems>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.InfiniteScrollList.<<LoadWork>b__7>d__9.Move
```

**Comment by stephenstroud** [comment]
The latest update (version 3.0.60.225.100)  just fixed the same issue for me.

**Comment by zhili1208** [comment]
this is not a gallery issue, will move to NuGet/Home
