### ISSUE TITLE
String was not recognized as a valid DateTime Visual Studio 2015 CTP 5/6

### ISSUE THREAD

**Issue by stephenstroud** [NuGet/NuGetGallery#2376]
Can't install any Nuget Packages - getting the following error, any help would be great.

![nugetissue](https://cloud.githubusercontent.com/assets/7649287/6398547/3fcdb1ae-bde4-11e4-858b-838ddd25a275.PNG)

System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.ParseMetadata(JObject metadata)
   at NuGet.Client.V3.VisualStudio.V3UIMetadataResource.<GetMetadata>b__f(JObject item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadata>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadata>d__3c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<CheckLicenseAcceptance>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()

**Comment by danliu** [comment]
This is a known issue and the fix is on the way.

**Comment by stephenstroud** [comment]
Awesome the update just released (3.0.60225.100) fixed it :+1:
