### ISSUE TITLE
`nuget install WpfLocalizeExtension` fails with "WARNING: Unexpected XML declaration."

### ISSUE THREAD

**Issue by jozefizso** [NuGet/NuGetGallery#2390]
I have problems with restoring/installing WpfLocalizeExtension package:

```
c:\dev>nuget install WpfLocalizeExtension -verbosity detailed
GET https://www.nuget.org/api/v2/FindPackagesById()?$filter=IsLatestVersion&$orderby=Version desc&$top=1&id='WpfLocalizeExtension'
GET https://www.nuget.org/api/v2/Packages(Id='WpfLocalizeExtension',Version='2.3')
WARNING: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 4, position 643.
System.InvalidOperationException: Unable to find version '2.3' of package 'WpfLocalizeExtension'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepository, IPackageRepository localRepository, IPackageConstraintProvider constraintProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVersions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.Commands.InstallCommand.InstallPackage(IFileSystem fileSystem, String packageId, SemanticVersion version)
   at NuGet.Commands.InstallCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

Response contains this invalid XML:

```
<?xml version="1.0" encoding="utf-8"?><entry xml:base="https://www.nuget.org/api/v2/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><id>https://www.nuget.org/api/v2/Packages(Id='WpfLocalizeExtension',Version='2.3')</id><category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" /><link rel="edit" title="V2FeedPackage" href="Packages(Id='WpfLocalizeExtension',Version='2.3')" /><title type="text">WpfLocalizeExtension</title><summary type="text">LocalizationExtension is a really easy way to localize any type of DependencyProperties or native Properties on DependencyObjects</summary><updated>2015-02-24T08:52:01Z</updated><author><name>Bernhard Millauer, Uwe Mayer</name></author><link rel="edit-media" title="V2FeedPackage" href="Packages(Id='WpfLocalizeExtension',Version='2.3')/$value" /><content type="application/zip" src="https://www.nuget.org/api/v2/package/WpfLocalizeExtension/2.3.0" /><m:properties><d:Version>2.3</d:Version><d:NormalizedVersion>2.3.0</d:NormalizedVersion><d:Copyright>Bernhard Millauer, Uwe Mayer</d:Copyright><d:Created m:type="Edm.DateTime">2015-02-24T08:46:45.827</d:Created><d:Dependencies>XAMLMarkupExtensions:1.2:</d:Dependencies><d:Description>LocalizationExtension is a really easy way to localize any type of DependencyProperties or native Properties on DependencyObjects</d:Description><d:DownloadCount m:type="Edm.Int32">16932</d:DownloadCount><d:GalleryDetailsUrl>https://www.nuget.org/packages/WpfLocalizeExtension/2.3.0</d:GalleryDetailsUrl><d:IconUrl></d:IconUrl><d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion><d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion><d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease><d:Language>en-US</d:Language><d:Published m:type="Edm.DateTime">2015-02-24T08:46:45.827</d:Published><d:PackageHash>UdtG8dNtzQO8zv47mV+mVe9IU9q/dj7qCcphxrRj+JF1aT8mlnzNS02ubXaoj7wZXQs/6fest9wJPecRhPYeMg==</d:PackageHash><d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm><d:PackageSize m:type="Edm.Int64">16019</d:PackageSize><d:ProjectUrl>https://github.com/SeriousM/WPFLocalizationExtension/</d:ProjectUrl><d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/WpfLocalizeExtension/2.3.0</d:ReportAbuseUrl><d:ReleaseNotes>v2.3
* closes #42
* closes #48
* refs #34</d:ReleaseNotes><d:RequireLicenseAcceptance m:type="Edm.Boolean">true</d:RequireLicenseAcceptance><d:Tags>wpf silverlight phone localization extension globalization resx csv resource language</d:Tags><d:Title>WPF Localization Extension</d:Title><d:VersionDownloadCount m:type="Edm.Int32">435</d:VersionDownloadCount><d:MinClientVersion></d:MinClientVersion><d:LastEdited m:type="Edm.DateTime">2015-02-24T08:48:58.477</d:LastEdited><d:LicenseUrl>https://github.com/SeriousM/WPFLocalizationExtension/blob/master/LICENSE</d:LicenseUrl><d:LicenseNames></d:LicenseNames><d:LicenseReportUrl></d:LicenseReportUrl></m:properties></entry><?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>500</m:code><m:message xml:lang="en-US">An error occurred while trying to write an error payload.</m:message><m:innererror><m:message>Cannot transition from state 'Completed' to state 'Error'. Nothing further can be written once the writer has completed.</m:message><m:type>Microsoft.Data.OData.ODataException</m:type><m:stacktrace>   at Microsoft.Data.OData.ODataWriterCore.Microsoft.Data.OData.IODataOutputInStreamErrorListener.OnInStreamError()&#xD;
   at Microsoft.Data.OData.Atom.ODataAtomOutputContext.WriteInStreamErrorImplementation(ODataError error, Boolean includeDebugInformation)&#xD;
   at Microsoft.Data.OData.Atom.ODataAtomOutputContext.WriteInStreamError(ODataError error, Boolean includeDebugInformation)&#xD;
   at System.Data.Services.ErrorHandler.WriteErrorWithFallbackForXml(ODataMessageWriter messageWriter, Encoding encoding, Stream responseStream, HandleExceptionArgs args, ODataError error, MessageWriterBuilder messageWriterBuilder)</m:stacktrace></m:innererror></m:error>
```

The `Install-Package WpfLocalizeExtension` run in Visual Studio installs the packages correctly (even if I clear the NuGet cache folder).

**Comment by jozefizso** [comment]
Installing the package using `Install-Package` works, but running `Update-Package -Reinstall` will fail:

```
PM> Install-Package WpfLocalizeExtension -Verbose
Attempting to resolve dependency 'XAMLMarkupExtensions (≥ 1.2)'.
Installing 'WpfLocalizeExtension 2.3'.
You are downloading WpfLocalizeExtension from Bernhard Millauer,  Uwe Mayer, the license agreement to which is available at https://github.com/SeriousM/WPFLocalizationExtension/blob/master/LICENSE. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Added file 'WPFLocalizeExtension.dll' to folder 'WpfLocalizeExtension.2.3\lib\net35'.
Added file 'WPFLocalizeExtension.xml' to folder 'WpfLocalizeExtension.2.3\lib\net35'.
Added file 'WP7LocalizeExtension.dll' to folder 'WpfLocalizeExtension.2.3\lib\sl4-wp71'.
Added file 'WP7LocalizeExtension.xml' to folder 'WpfLocalizeExtension.2.3\lib\sl4-wp71'.
Added file 'SLLocalizeExtension.dll' to folder 'WpfLocalizeExtension.2.3\lib\sl50'.
Added file 'SLLocalizeExtension.xml' to folder 'WpfLocalizeExtension.2.3\lib\sl50'.
Added file 'WpfLocalizeExtension.2.3.nupkg' to folder 'WpfLocalizeExtension.2.3'.
Successfully installed 'WpfLocalizeExtension 2.3'.
Adding 'XAMLMarkupExtensions 1.2' to Project1.
For adding package 'XAMLMarkupExtensions 1.2' to project 'Project1' that targets 'net45',
>> Assembly references are being added from 'lib\net40'
Added reference 'XAMLMarkupExtensions' to project 'Project1'
Added file 'packages.config'.
Successfully added 'XAMLMarkupExtensions 1.2' to Project1.
Adding 'WpfLocalizeExtension 2.3' to Project1.
For adding package 'WpfLocalizeExtension 2.3' to project 'Project1' that targets 'net45',
>> Assembly references are being added from 'lib\net35'
Added reference 'WPFLocalizeExtension' to project 'Project1'
Added file 'packages.config'.
Successfully added 'WpfLocalizeExtension 2.3' to Project1.
```

```
PM> Update-Package -Reinstall WpfLocalizeExtension -Verbose
Removing 'WpfLocalizeExtension 2.3' from Project1.
Removed reference 'WPFLocalizeExtension.dll' from project 'Project1'
Added file 'packages.config'.
Successfully removed 'WpfLocalizeExtension 2.3' from Project1.
Removing 'XAMLMarkupExtensions 1.2' from Project1.
Removed reference 'XAMLMarkupExtensions.dll' from project 'Project1'
Added file 'packages.config'.
Successfully removed 'XAMLMarkupExtensions 1.2' from Project1.
Uninstalling 'WpfLocalizeExtension 2.3'.
Removed file 'WP7LocalizeExtension.dll' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl4-wp71'.
Removed file 'WP7LocalizeExtension.xml' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl4-wp71'.
Removed folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl4-wp71'.
Removed file 'WPFLocalizeExtension.dll' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\net35'.
Removed file 'WPFLocalizeExtension.xml' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\net35'.
Removed folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\net35'.
Removed file 'SLLocalizeExtension.dll' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl50'.
Removed file 'SLLocalizeExtension.xml' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl50'.
Removed folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib\sl50'.
Removed folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3\lib'.
Removed file 'WpfLocalizeExtension.2.3.nupkg' to folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3'.
Removed folder 'D:\dev\Project1\packages\WpfLocalizeExtension.2.3'.
Successfully uninstalled 'WpfLocalizeExtension 2.3'.
Update-Package : Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 4, position 643.
At line:1 char:1
+ Update-Package -Reinstall WpfLocalizeExtension -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
 ```

**Comment by yishaigalatzer** [comment]
@RanjiniM @johnataylor can we see if this related to the syncing index and database?

**Comment by yishaigalatzer** [comment]
@jozefizso can you please tell us what version of Visual studio and nuget client are you using?

**Comment by jozefizso** [comment]
I use NuGet.exe version 2.8.50926.602 from command line on build server and Visual Studio 2013 Update 4 Ultime with Nuget Package Manager version 2.8.50926.663.

**Comment by RanjiniM** [comment]
On investigation, this package seems to fail only from nuget.org. Installing 2.3 from api.nuget.org (v3 feed) works but fails to install from nuget.org (v2 feed)

**Comment by johnataylor** [comment]
This is the same issue as we see on MSGReader.

Initial analysis suggests this is caused by duplicate entries in the Lucene index.

**Comment by yishaigalatzer** [comment]
@jozefizso we should have a fix shortly for this (this week I hope)

**Comment by maartenba** [comment]
I have deployed a fix to http://int.nugettest.org, pointing to production data. Can you try using http://int.nugettest.org/api/v2 as the package source and see if this fixes the issue?
