### ISSUE TITLE
NuGet.exe 2.8 fails to push the package, while NuGet.exe 2.7 succeeds

### ISSUE THREAD

**Issue by yansklyarenko** [NuGet/NuGetGallery#2447]
I have a NuGet feed hosted in Inedo's ProGet. When I push a package with NuGet.exe version **2.8.x** (the latest available) larger than 1 MB to that feed, I get the following error:

```
System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot close str
eam until all bytes are written.
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
   at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
   at System.Net.ConnectStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at NuGet.MultipartWebRequest.CreateMultipartRequest(WebRequest request)
   at NuGet.PackageServer.<>c__DisplayClass6.<PushPackageToServer>b__5(Object sender, WebRequestEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at NuGet.HttpClient.RaiseSendingRequest(WebRequest webRequest)
   at NuGet.RequestHelper.GetResponse(Func`1 createRequest, Action`1 prepareRequest, IProxyCache proxyCache, ICredential
Cache credentialCache, ICredentialProvider credentialProvider)
   at NuGet.HttpClient.GetResponse()
   at NuGet.PackageServer.EnsureSuccessfulResponse(HttpClient client, Nullable`1 expectedStatusCode)
   at NuGet.PackageServer.PushPackageToServer(String apiKey, Func`1 packageStreamFactory, Int64 packageSize, Int32 timeo
ut)
   at NuGet.PackageServer.PushPackage(String apiKey, IPackage package, Int64 packageSize, Int32 timeout)
   at NuGet.Commands.PushCommand.PushPackageCore(String source, String apiKey, PackageServer packageServer, String packa
geToPush, TimeSpan timeout)
   at NuGet.Commands.PushCommand.PushPackage(String packagePath, String source, String apiKey, TimeSpan timeout)
   at NuGet.Commands.PushCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

The command like I run is simple:

```
nuget.exe push "MyPackage.nupkg" -s "http://progetserver/nuget/feedname" -Verbosity detailed -NonInteractive -Timeout 40
```
However, if I run the same command with NuGet.exe version **2.7.x** (latest available), it works just fine!

With the help of Inedo's support team I managed to emulate the PUT request NuGet.exe is issuing in order to push the package, and it succeeds, too. 

So, it looks like something has changed between 2.8 and 2.7 in this matter. This is a quote of Inedo's engineer:

> From looking through the NuGet source code, they appear to have written the client in a very asynchronous manner, and given the odd network-specific errors we are seeing here, this suggests to me that they have some kind of race condition where _sometimes_ the connection is closed prematurely (i.e. one thread/task is still writing the last chunk of data to the underlying socket while another thread/task closes it). Introducing the Fiddler proxy changes the timing and so "fixes" the issue. This is just a wild guess, but it fits with what we are seeing.

**Comment by bhuvak** [comment]
Moving to home repo. Closing this one.

**Comment by bhuvak** [comment]
@yansklyarenko , does it happen consistently ? I am working on fixing and am able to upload packages up to 150 MB without any issue. Also what happens if the "Timeout" value is increased ?

**Comment by yansklyarenko** [comment]
It does happen consistently when the command runs across physical locations. We have ProGet server in Denmark, while clients across the globe, e.g. in Ukraine. If you push a package larger than 1MB from UA to DK, it fails with the error I mentioned above (v2.8). If NuGet.exe version is 2.7, it works just fine. Increasing the Timeout value just results in a longer delay, and then it fails with the same error.

**Comment by maartenba** [comment]
@yansklyarenko can you try setting the Timeout argument to a different that is an uneven number, e.g. "123"?

**Comment by bhuvak** [comment]
@yansklyarenko, also does it happen only with ProGet server or with nuget.org as well ?

**Comment by bhuvak** [comment]
@yansklyarenko, I tried uploading packages from different regions ( West US and Europe) and push succeeds for bigger packages. If the issue persists on your end, please re open  https://github.com/NuGet/Home/issues/535 with more details around the above questions.

**Comment by larsbrinkhoff** [comment]
I have the same issue.  Should I assist with information?
