### ISSUE TITLE
Error update-database

### ISSUE THREAD

**Issue by Darknet** [NuGet/NuGetGallery#2724]
Hi everyone,

I've a problems with nuget gallery.

When i try build.cmd, return this error:

Project "C:\NugetGallery\packages\NuGet.Services.Build.3.0.9\tools\NuGet.Services.FullBuild.msbuild" (2) is building "C:\NugetGallery\NuGetGallery.sln" (3) on node 1 (Build target(s)).
C:\NugetGallery\NuGetGallery.sln(2,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 2, position 1.
Done Building Project "C:\NugetGallery\NuGetGallery.sln" (Build target(s)) -- FAILED.

Done Building Project "C:\NugetGallery\packages\NuGet.Services.Build.3.0.9\tools\NuGet.Services.FullBuild.msbuild" (default targets) -- FAILED.

Done Building Project "C:\NugetGallery\build.msbuild" (default targets) -- FAILED.
Build FAILED.

"C:\NugetGallery\build.msbuild" (default target) (1) ->
"C:\NugetGallery\packages\NuGet.Services.Build.3.0.9\tools\NuGet.Services.FullBuild.msbuild" (default target) (2) ->"C:\NugetGallery\NuGetGallery.sln" (Build target) (3) ->
  C:\NugetGallery\NuGetGallery.sln(2,1): error MSB4025: The project file couldnot be loaded. Data at the root level is invalid. Line 2, position 1.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.52

Ok not problem Open Solution and build.

Works fine compile 8 projects.

next step database, on README.md file put this line 

Update-Database -StartUpProjectName NuGetGallery

add -verbose, for more control, and appear this error

Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
You can use the Add-Migration command to write the pending model changes to a code-based migration.

Ok any problem,, on file Migrationsconfigurations.cs change             
AutomaticMigrationsEnabled from false to true.

the same Update-Database -StartUpProjectName NuGetGallery -verbose

after a lots of create, insert, etc,

The Fatal Error from Database

Applying automatic migration: 201510081058308_AutomaticMigration.
CREATE INDEX [IX_UserKey] ON [dbo].[Credentials]([UserKey])
System.Data.SqlClient.SqlException (0x80131904): The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
ClientConnectionId:747c0e44-4366-4801-9f74-bd3a453ccd01
Error Number:1913,State:1,Class:16
The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.

anybody help me??

Thanks

P.D Database is SQL SERVER EXPRESS 2012

**Comment by maartenba** [comment]
Can you try running `Update-Database -StartUpProjectName NuGetGallery -TargetMigration 201508031046581_IndexPackagesLastUpdatedWithIsListed`

**Comment by Darknet** [comment]
after apply this appear this

Target database is already at version 201508031046581_IndexPackagesLastUpdatedWithIsListed.

the next step is publish the solution.

right???

**Comment by maartenba** [comment]
Yes it is :)

**Comment by Darknet** [comment]
ok thanks in advance i will try

**Comment by Darknet** [comment]
works fine thansk

**Comment by Darknet** [comment]
can you tell me if it's `possible the integration with Active Directory???
