### ISSUE TITLE
unable to create database using Update-Database.The operation failed because an index or statistics with name 'IX_UserKey' already exists 

### ISSUE THREAD

**Issue by ashuthinks** [NuGet/NuGetGallery#2748]
unable to create database using Update-Database -StartUpProjectName NuGetGallery

getting following error:

The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.

I searched for name 'IX_UserKey' in Migration but I don't find it :(

**Comment by maartenba** [comment]
Is that a fresh database?

**Comment by ashuthinks** [comment]
yes its a fresh new database , cab you provide me sql scripts for the same?

**Comment by maartenba** [comment]
Update-Database should do the trick, it does for me. Can you make sure to run it on an empty database?

**Comment by ashuthinks** [comment]
I'm doing anything wrong .
in web.config
  <connectionStrings>
       <add name="NuGetGallery"
        connectionString="Data Source=.\SQLEXPRESS;Initial Catalog=NuGetGallery;Integrated Security=SSPI;
User ID=sa;Password=demopassword;" />
  </connectionStrings>

in package manager console
package source - nuget.org
default project - NuGetGallery
in ssms I have created new empty database - NugetGallery

please guide me

**Comment by maartenba** [comment]
Then Update-Database should do it. Can you run:
```Update-Database -Verbose``` and paste the output?

**Comment by ashuthinks** [comment]
PM> Update-Database -Verbose
Using StartUp project 'NuGetGallery'.
Using NuGet project 'NuGetGallery'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'Gallery.SqlServer' (DataSource: (localdb)\v11.0, Provider: System.Data.SqlClient, Origin: Convention).
No pending explicit migrations.
Applying automatic migration: 201510281548109_AutomaticMigration.
CREATE INDEX [IX_UserKey] ON [dbo].[Credentials]([UserKey])
System.Data.SqlClient.SqlException (0x80131904): The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
ClientConnectionId:0be5ccf7-10b3-46d1-9582-861906169a2a
Error Number:1913,State:1,Class:16
The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.

**Comment by maartenba** [comment]
Seems you already have everything you need in the database OR you enabled automatic migrations, which should be off.

The output should not contain `Applying automatic migration: 201510281548109_AutomaticMigration.`

Did you download latest sources from master branch?

**Comment by ashuthinks** [comment]
yes I have downloaded latest source from master branch (if you suggest any other link plesae provide)
yes i have already on automatic migration from following 
 public MigrationsConfiguration()
        {
            AutomaticMigrationsEnabled = true;
        }
If I made it false and run PM> Update-Database -Verbose then following output I get.
PM> Update-Database -Verbose
Using StartUp project 'NuGetGallery'.
Using NuGet project 'NuGetGallery'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'Gallery.SqlServer' (DataSource: (localdb)\v11.0, Provider: System.Data.SqlClient, Origin: Convention).
No pending explicit migrations.
Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.
You can use the Add-Migration command to write the pending model changes to a code-based migration.

**Comment by maartenba** [comment]
You may want to clean the database once more.

**Comment by ashuthinks** [comment]
clean? sorry didn't get you. database is empty

**Comment by maartenba** [comment]
Can you Run Add-Migration "TEST" and then Update-Database?

**Comment by ashuthinks** [comment]
same issue :(

PM> Add-Migration "TEST" 
Re-scaffolding migration 'TEST'.
PM> Update-Database -Verbose
Using StartUp project 'NuGetGallery'.
Using NuGet project 'NuGetGallery'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'Gallery.SqlServer' (DataSource: (localdb)\v11.0, Provider: System.Data.SqlClient, Origin: Convention).
Applying explicit migrations: [201510281614599_TEST].
Applying explicit migration: 201510281614599_TEST.
CREATE INDEX [IX_UserKey] ON [dbo].[Credentials]([UserKey])
System.Data.SqlClient.SqlException (0x80131904): The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
ClientConnectionId:f87e6195-3461-4331-86bf-a7ebc62bbb04
Error Number:1913,State:1,Class:16
The operation failed because an index or statistics with name 'IX_UserKey' already exists on table 'dbo.Credentials'.
PM>

**Comment by maartenba** [comment]
Any tables in your database now? Looks like the yshould be there.

**Comment by ashuthinks** [comment]
No :( not a single table . why so? i'm wrong any where ? connection string ?

**Comment by maartenba** [comment]
No idea to be honest, this should work smoothly, at least last time I tried it a few days back.
Can you try running the target migration right before "TEST" (something with deletes if I recall correctly)
Update-Database -TargetMigration "name of that migration"

**Comment by ashuthinks** [comment]
ok let me try will update you thanks , if you got to remember anything that i missed here please update me

**Comment by ashuthinks** [comment]
Bingo Tables created but error is still same , now what to do?

**Comment by maartenba** [comment]
Just run the solution if the tables are there :)

**Comment by ashuthinks** [comment]
Another issue not getting confirmation email :(

**Comment by maartenba** [comment]
Check the readme, it should be in App_Data :)

**Comment by ashuthinks** [comment]
awesome working great, is there a bulk upload?

**Comment by maartenba** [comment]
nuget push * apikey -source http://nuget.localtest.me/api/package

**Comment by ashuthinks** [comment]
thanks

**Comment by ashuthinks** [comment]
what is this http://nuget.localtest.me/api/package??

**Comment by maartenba** [comment]
The URL to where your gallery is running and where you can push packages.

**Comment by ashuthinks** [comment]
it must be the name of my azure website name where I have hosted "NugetGallery" Web Project? and from where I get apikey  , I just tried with key="reCAPTCHA::PrivateKey" value inside apikey but getting  error 
Failed to process request. 'The specified API key is invalid or does not have pe
rmission to access the specified package.'.
The remote server returned an error: (403) Forbidden..
My full execute command - 
C:\MyPackages\nuget push * value_from_reCAPTCHA::PrivateKey -source http://mydemowebsite.azurewebsites.net/

**Comment by ashuthinks** [comment]
Got you thanks

**Comment by ashuthinks** [comment]
this is not working nuget push * myapikey -source http://nuget.localtest.me/api/package
but this is working nuget push * bfb53992-6518-4c93-9c86-54e647c4d523 -source http://myazurewebsite

**Comment by ashuthinks** [comment]
should I use " http://nuget.localtest.me/api/package" or my azure website?

**Comment by ashuthinks** [comment]
where exactly my .nupkg files uploaded ? where to check in FTP?
