### ISSUE TITLE
Message=Keyword not supported: ssl

### ISSUE THREAD

**Issue by squalo-villa** [NuGet/NuGetGallery#2776]
Hi all,
I had a related issue, I'm trying to connect to a postgres DB on Heroku and I'm getting this error:

System.ArgumentException was unhandled
HResult=-2147024809
Message=Keyword not supported: ssl
Parameter name: keyword
ParamName=keyword
Source=Npgsql
StackTrace:
at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword)
at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
at Npgsql.NpgsqlConnection..ctor(String connectionString)
at OutlookSynchronizer.TestClass.Main(String[] args) in c:\users\cloudreach\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\TestClass.cs:line 11
at System.AppDomain.nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
at System.Threading.ThreadHelper.ThreadStartContext(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
InnerException:

cga, I've tried also your snippet above and I got this same error.
I'm using Npgsql version 3.0.3.0, RuntimeVersion: v4.0.30319

Might this be something related to the latest release/version?

Thanks,
Diego

**Comment by maartenba** [comment]
Please check with the package owner directly. We only deliver the packages, building them and maintaining them is out of our hands :)
