### ISSUE TITLE
More than one migrations configuration type was found in the assembly 'NuGetGallery'

### ISSUE THREAD

**Issue by cmcknz77** [NuGet/NuGetGallery#2923]
I'm setting up Nuget Gallery for first time and am following the steps in this document: https://github.com/NuGet/NuGetGallery/wiki/Hosting-the-NuGet-Gallery-Locally-in-IIS
I have successfully installed IIS and created the Website http://localhost/Gallery
I have also successfully installed SQLExpress2014 and am using the following as my connectionstring for the destination database:
"Data Source=.\SQLEXPRESS;Initial Catalog=master;Integrated Security=True"
 
But when I ran Update-Database command to create the DB I get below error:

PM>  Update-Database -StartUpProjectName NuGetGallery -debug -verbose
Using StartUp project 'NuGetGallery'.
Using NuGet project 'NuGetGallery'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
System.Data.Entity.Migrations.Infrastructure.MigrationsException: More than one migrations configuration type was found in the assembly 'NuGetGallery'. Specify the name of the one to use.
   at System.Data.Entity.Utilities.TypeFinder.FindType(Type baseType, String typeName, Func`2 filter, Func`2 noType, Func`3 multipleTypes, Func`3 noTypeWithName, Func`3 multipleTypesWithName)
   at System.Data.Entity.Migrations.Utilities.MigrationsConfigurationFinder.FindMigrationsConfiguration(Type contextType, String configurationTypeName, Func`2 noType, Func`3 multipleTypes, Func`3 noTypeWithName, Func`3 multipleTypesWithName)
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.FindConfiguration()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.GetMigrator()
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
More than one migrations configuration type was found in the assembly 'NuGetGallery'. Specify the name of the one to use.
 
Can anyone help?   I have followed through this document https://github.com/NuGet/NuGetGallery/issues/1108 but I cannot see how to 'exclude' /src/Migrations/configuration.cs without deleting it and if I do that the project refuses to build.

**Comment by xavierdecoster** [comment]
Use `Update-Database -ConfigurationTypeName MigrationsConfiguration`. We have a second migrations configuration in the admin area for a support requests database which you likely won't need, and which is likely to be pulled out of the gallery code base at some point.

Closing the issue, but feel free to reply here if you encounter further issues.

**Comment by cmcknz77** [comment]
Boom... Thank you Xavier ;-) I confirm that that's got it.

**Comment by maartenba** [comment]
@xavierdecoster Can you update the gallery readme?

**Comment by xavierdecoster** [comment]
Done https://github.com/NuGet/NuGetGallery/commit/4e3f1fd75218ee8e060770850a20539465234321
