### ISSUE TITLE
Getting Error while deploying Nuget Server with Latest version in IIS

### ISSUE THREAD

**Issue by irfspy** [NuGet/NuGetGallery#3079]
While deploying the Nuget Server with latest version 2.11.2 to IIS. Getting the below error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code/>
<message xml:lang="en-US">An error occurred while processing this request.</message>
<innererror>
<message>Method not found: '!!0[] System.Array.Empty()'.</message>
<type>System.MissingMethodException</type>
<stacktrace>
at NuGet.Server.Infrastructure.ServerPackageRepository.SetupBackgroundJobs()
 at NuGet.Server.Infrastructure.ServerPackageRepository.get_CachedPackages()
 at NuGet.Server.Infrastructure.ServerPackageRepository.GetPackages()
 at NuGet.Server.DataServices.PackageContext.get_Packages()
 at queryable_reader(Object )
 at System.Data.Services.Providers.ReflectionServiceProvider.GetResourceContainerInstance(ResourceSet resourceContainer)
 at System.Data.Services.RequestUriProcessor.CreateFirstSegment(IDataService service, String identifier, Boolean checkRights, String queryPortion, Boolean isLastSegment, Boolean& crossReferencingUrl)
 at System.Data.Services.RequestUriProcessor.CreateSegments(String[] segments, IDataService service)
 at System.Data.Services.RequestUriProcessor.ProcessRequestUri(Uri absoluteRequestUri, IDataService service)
 at System.Data.Services.DataService`1.HandleRequest()
</stacktrace>
</innererror>
</error>

Locally it is working fine. I tried same procedure with Nuget.Server v2.11.1 and it is working fine after deploying to IIS, able to view packages.

**Comment by maartenba** [comment]
Make sure you have .NET 4.6 on your server

**Comment by irfspy** [comment]
yes i already checked framework 4.6 is there. Even If I deploy Nuget.Server v2.11.1 trageting 4.6 framework its working fine but Latest version Nuget.Server V2.11.2 giving the above error.

**Comment by maartenba** [comment]
That does look like [.NET framework 4.6](https://msdn.microsoft.com/en-us/library/5a4x27ek(v=vs.110).aspx) is missing on the server (or the application pool is not using it). The `System.Array.Empty()` is new in mscorlib 4.6.

**Comment by irfspy** [comment]
But I am not getting one thing that out of two application in 4.6 framework pointing to same app pool
one is working and another not. Is any extra configuration needed in IIS for Nuget.Server v2.11.2 as I told above v2.11.1 is working.

**Comment by maartenba** [comment]
2.11.1 targeted .NET 4.5, 2.12.2 targets 4.6. You can safely use 2.11.1 instead (the only change with 2.11.2 was the explicit dependency on 4.6, other than that both are identical)

**Comment by irfspy** [comment]
Thanks you for you support! I will try and hope the problem resolves.

**Comment by irfspy** [comment]
Thank you for you support! I will try and hope the problem resolves.

**Comment by maartenba** [comment]
Thanks, do keep us posted!
