### ISSUE TITLE
HandlePackageEdits job - endlessly handling an invalid edit

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3102]
In dev environment: 
Rewriting package file for WebActivator 1.0.0
[Info]:     [2016-06-29T18:14:48.0939399Z]: Error editing package WebActivator 1.0.0: System.ComponentModel.DataAnnotations.ValidationException: LicenseUrl cannot be empty.
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.Save(Stream stream, Boolean validate, Int32 minimumManifestVersion)
   at NuGet.Manifest.Save(Stream stream)
   at HandlePackageEdits.Job.<ApplyEdit>d__49.MoveNext() in C:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HandlePackageEdits.Job.<Run>d__47.MoveNext() in C:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 133

**Comment by skofman1** [comment]
The issue is caused because the gallery doesn't verify the correctness of a package in the same way nuget.exe pack does. So, for example, packages with empty LicenseUri can be pushed successfully. However, subsequent edits of those packages will fail, because the job HandlePackageEdits verifies nuspec correctness in the same way nuget.exe does.

Suggested fix: gallery should verify package correctness.

**Comment by maartenba** [comment]
Looks related to https://github.com/NuGet/NuGetGallery/issues/2150

**Comment by maartenba** [comment]
@skofman1 @shishirx34 Can this one be closed?

**Comment by skofman1** [comment]
Lets close it when it's in production (not yet).
