### ISSUE TITLE
Validation job - System.ArgumentException: Messages cannot be larger than 65536 bytes

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3120]
Error when validating https://www.nuget.org/packages/Aspose.Imaging/3.8.0 (due to large release notes field). @skofman1 @xavierdecoster should we truncate release notes for the validation process (we don't currently use the value so might as well just skip the field being added)?

Stacktrace:
```
Validation.Runner.exe Error: 0 : [FAILED]: System.ArgumentException: Messages cannot be larger than 65536 bytes.
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.GetMessageContentForTransfer(Boolean shouldEncodeMessage, QueueRequestOptions options) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Queue\CloudQueueMessage.Common.cs:line 285
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageImpl(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 2567
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.BeginAddMessage(CloudQueueMessage message, Nullable`1 timeToLive, Nullable`1 initialVisibilityDelay, QueueRequestOptions options, OperationContext operationContext, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1356
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.BeginAddMessage(CloudQueueMessage message, AsyncCallback callback, Object state) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1333
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.TaskFromVoidApm[T1](Func`4 beginMethod, Action`1 endMethod, T1 arg1, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 174
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message, CancellationToken cancellationToken) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1394
   at Microsoft.WindowsAzure.Storage.Queue.CloudQueue.AddMessageAsync(CloudQueueMessage message) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Queue\CloudQueue.cs:line 1382
   at NuGet.Jobs.Validation.Common.PackageValidationQueue.<EnqueueAsync>d__5.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\Validation.Common\PackageValidationQueue.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Validation.Common.PackageValidationService.<StartValidationProcessAsync>d__5.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\Validation.Common\PackageValidationService.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.Jobs.Validation.Runner.Job.<RunOrchestrateAsync>d__10.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\Validation.Runner\Job.cs:line 255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Validation.Runner.Job.<Run>d__8.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\Validation.Runner\Job.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<JobLoop>d__6.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<Run>d__2.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 66
```

**Comment by skofman1** [comment]
Can you please provide more details about the job? What's the scenario? What do we push to the queue?

**Comment by maartenba** [comment]
THe package metadata is enqueued to our various validators like virus scan. Virus scan doesn't really need release notes to do its thig

**Comment by skofman1** [comment]
We should also remove description, copyright, LicenseUrl, ProjectUrl, Summary, tags  (that are limited to 4000 chars in the DB).
I'm basing this on the documentation here: https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery.Core/Entities/Package.cs#L37

**Comment by maartenba** [comment]
Sounds good! Truncate it to a max length (e.g. 1000 chars) or simply not add the data?

**Comment by skofman1** [comment]
I think either way will keep us safely away from 65536 bytes :sunglasses:

**Comment by maartenba** [comment]
Opened a PR. Decided to keep the data in our audits, but truncate it for processing in the queue.
