### ISSUE TITLE
Exception causes Stats.CollectAzureCdnLogs to stop running

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3121]
Issue happened in dev environment. Exception call stack from AI:

```

stats.collectazurecdnlogs.exe Error: 0 :
[FAILED]: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (503) Server Unavailable. ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.Exists(Boolean primaryOnly, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 1417
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 199
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 184
   at NuGet.Jobs.AzureBlobJobTraceListener..ctor(String jobName, String primaryStorageAccount) in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\Tracing\AzureBlobJobTraceListener.cs:line 70
   at NuGet.Jobs.JobRunner.SetJobTraceListener(JobBase job, Boolean consoleLogOnly, IDictionary`2 argsDictionary) in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 123
   at NuGet.Jobs.JobRunner.<>c__DisplayClass4_1.<Run>b__0(JobBase j) in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 80
   at NuGet.Jobs.JobRunner.<JobLoop>d__8.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 204
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<Run>d__4.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 80
Request Information
RequestID:f1505e2c-0001-0045-522c-dc0f02000000
RequestDate:Tue, 12 Jul 2016 11:01:16 GMT
StatusMessage:The server is busy.
```

**Comment by skofman1** [comment]
Same thing happend in INT: 
```
stats.collectazurecdnlogs.exe Error: 0 :
[FAILED]: Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 677
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 604
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.Exists(Boolean primaryOnly, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 1417
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobContainerPublicAccessType accessType, BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 199
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExists(BlobRequestOptions requestOptions, OperationContext operationContext) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlobContainer.cs:line 184
   at NuGet.Jobs.AzureBlobJobTraceListener..ctor(String jobName) in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\Tracing\AzureBlobJobTraceListener.cs:line 71
   at NuGet.Jobs.JobRunner.SetJobTraceListener(JobBase job, Boolean consoleLogOnly) in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 111
   at NuGet.Jobs.JobRunner.<JobLoop>d__6.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<Run>d__2.MoveNext() in D:\BuildAgent\work\ab85ff06568d51d2\src\NuGet.Jobs.Common\JobRunner.cs:line 66
Request Information
RequestID:4950b986-0001-0055-2a2e-d99c9b000000
RequestDate:Fri, 08 Jul 2016 15:35:17 GMT
StatusMessage:The value for one of the HTTP headers is not in the correct format.
```

**Comment by scottbommarito** [comment]
The `AzureBlobJobTraceListener` constructor has the following code in it outside a `try-catch`...

```
var logStorageAccount = CloudStorageAccount.Parse(primaryStorageAccount);
_logStorageContainer = logStorageAccount.CreateCloudBlobClient().GetContainerReference(_logStorageContainerName);
_logStorageContainer.CreateIfNotExists();
```

Occasionally, this initialization can fail (like it did here). When that happens, the failure propagates all the way to `JobRunner.Run` and causes the job to exit. If the AzureBlobJobTraceListener fails to initialize, the `JobRunner` should not exit and should continue looping the job anyway, attempting to construct it again on a future run.

**Comment by yishaigalatzer** [comment]
Keep in mind the following

1. Exponential backoffs
2. Eventual failure (if after a certain amount of retries we fail, do exit the job)
3. Alterting/logging
