### ISSUE TITLE
NuGet.server crashes when package id is from GB18030 char-set

### ISSUE THREAD

**Issue by maartenba** [NuGet/NuGetGallery#3159]
_From @mishra14 on July 22, 2016 23:14_

Repro - 

Start a nuget.server. Add a package with id from GB18030 char-set (e.g. - 㐀㒣㕴㕵㙉㙊䵯䵰䶴䶵).

The server throws unhandled exception soon after or on adding a new package.

The cause could be due to the move away from nuget core(?)

_Copied from original issue: NuGet/Home#3200_

**Comment by scottbommarito** [comment]
I had a really weird time repro'ing this.

The first time I booted up the gallery and added a package with GB18030 characters it crashed immediately, with an unhandled exception that said that it didn't have permission to create a directory at https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Services/FileSystemFileStorageService.cs#L146.

Seeing that this was a local filesystem issue, I decided to boot up the cloud service and see if any issue would occur. As I expected, nothing happened; however, when I went back to the local server, I could no longer repro any issue, and the package that had crashed while uploading was successfully on the gallery. I think the gallery issue I encountered was probably unrelated to GB18030, and maybe just a fluke during startup.

I tried to test NuGet.Server, but I think I must not have it set up correctly because it gave me an exception every single time I tried to upload a package, regardless of whether or not GB18030 characters were included. It popped up at https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Publishing/PackageService.cs#L46:

"An exception of type 'System.IO.FileFormatException' occurred in WindowsBase.dll but was not handled in user code

Additional information: File contains corrupted data."

This seemed quite odd to me because I was able to open the temporary file in several editors and verify the data seemed ok.

**Comment by maartenba** [comment]
On https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Services/FileSystemFileStorageService.cs#L146: can you verify `App_Data` is writable? Also do other package uploads work?

On https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Publishing/PackageService.cs#L46, that's super weird. Feel free to send over the package(s) you are trying to upload.

**Comment by scottbommarito** [comment]
On https://github.com/NuGet/NuGetGallery/blob/dev/src/NuGetGallery/Services/FileSystemFileStorageService.cs#L146: it only failed once, and then the remainder of times it would work fine. Even when I restarted the server after its first failure, it didn't fail again when uploading the same package or other packages with GB18030 characters. Seemed like a fluke to me.

On https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/Publishing/PackageService.cs#L46: everything I tried to upload failed, so I thought it was probably some kind of configuration issue. I'll send you a mail.

**Comment by mishra14** [comment]
@maartenba @scottbommarito : Any updates on this?

Thanks 

//cc: @rrelyea

**Comment by maartenba** [comment]
@scottbommarito did we manage to reproduce this one?

**Comment by scottbommarito** [comment]
If I remember correctly I wasn't able to configure `NuGet.Server` to try to repro because I hadn't worked with it before. I did verify that it didn't repro on the `NuGetGallery`.

**Comment by maartenba** [comment]
@mishra14 Can you try setting up a NuGet.Server using our latest prerelease and test in there?

``` Install-Package NuGet.Server -Version 2.14.0-dev-0003 -Source https://dotnet.myget.org/F/nuget-build/api/v2 ```

**Comment by mishra14** [comment]
@maartenba : 


[㕵㙉㙊䵯䵰䶴䶵.1.0.0.zip](https://github.com/NuGet/NuGetGallery/files/473211/1.0.0.zip)


I tried it with the prerelease. When I added the attached package (inside the zip) to the packagePath and refreshed - 

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code/>
<m:message xml:lang="en-US">An error has occurred.</m:message>
<m:innererror>
<m:message>
Part URI is not valid per rules defined in the Open Packaging Conventions specification.
</m:message>
<m:type>System.ArgumentException</m:type>
<m:stacktrace>
at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
 at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
 at System.IO.Packaging.Package.GetPart(Uri partUri)
 at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
 at NuGet.OptimizedZipPackage.EnsureManifest()
 at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
 at NuGet.Server.Core.Infrastructure.ServerPackageRepository.AddPackagesFromDropFolder()
 at NuGet.Server.Core.Infrastructure.ServerPackageRepository.RebuildPackageStore()
 at NuGet.Server.Core.Infrastructure.ServerPackageRepository.get_CachedPackages()
 at NuGet.Server.Core.Infrastructure.ServerPackageRepository.GetPackages()
 at NuGet.Server.V2.Controllers.NuGetODataController.Get(ODataQueryOptions`1 options)
 at lambda_method(Closure , Object , Object[] )
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
</m:stacktrace>
</m:innererror>
</m:error>
```

**Comment by maartenba** [comment]
Looks like an invalid package. NuGet Package Explorer (https://npe.codeplex.com/) is also unabl to load this package.

@joelverhagen @rrelyea @emgarten  do you have an idea what may be wrong with [this package](https://github.com/NuGet/NuGetGallery/files/473211/1.0.0.zip)?

**Comment by emgarten** [comment]
NuGet.Core.dll has trouble opening packages with localized ids and NPE uses that. NuGet 3.5.0 libraries should support this package, update NuGet.Server to use those :smile:

**Comment by maartenba** [comment]
Thanks :-) In that case, @mishra14 here's the tracking issue: https://github.com/NuGet/NuGetGallery/issues/3123

**Comment by maartenba** [comment]
Not sure this is still relevant.
