### ISSUE TITLE
HandlePackageEdits failing on Production for AspNetCore.Identity.RavenDb packages

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#3240]
Application insights shows following exception for a few package edits.

Packages:
- AspNetCore.Identity.RavenDB 1.0.0-alpha2
- AspNetCore.Identity.RavenDB 1.0.0-alpha3
- AspNetCore.Identity.RavenDB 1.0.0-alpha4
- AspNetCore.Identity.RavenDB 1.0.0-alpha5
- AspNetCore.Identity.RavenDB 1.0.0-alpha6

```
Error editing package AspNetCore.Identity.RavenDB 1.0.0-alpha2
System.NullReferenceException: Object reference not set to an instance of an object.
   at HandlePackageEdits.Job.<UpdateDatabaseWithEdit>d__50.MoveNext() in E:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 284
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at HandlePackageEdits.Job.<ApplyEdit>d__49.MoveNext() in E:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at HandlePackageEdits.Job.<Run>d__48.MoveNext() in E:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 145
```

Also the number of retries are over 25K. We should set the retry limit. It seems we never deployed/merged the changes for retry limit. https://github.com/NuGet/NuGet.Jobs/pull/53

**Comment by shishirx34** [comment]
The exception logged in the edits database, seems the edit for these packages are missing authors:

```
System.ComponentModel.DataAnnotations.ValidationException: Authors is required.
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at HandlePackageEdits.Job.<ApplyEdit>d__49.MoveNext() in C:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at HandlePackageEdits.Job.<Run>d__47.MoveNext() in C:\Nuget\NuGet.Jobs\src\HandlePackageEdits\HandlePackageEdits.Job.cs:line 133
```
