### ISSUE TITLE
HTTP 405 (Method Not Allowed) when pushing to nuget.org

### ISSUE THREAD

**Issue by splatteredbits** [NuGet/NuGetGallery#3334]
I'm getting a 405 (Method Not Allowed) HTTP error when publishing to nuget.org [1]. I'm on Windows 7, nuget.exe 3.4.4.1321. MTR trace at the bottom [2].

[1]
```
NuGet.exe push LibGit2.PowerShell.0.2.0.nupkg -ApiKey ******** -Source nuget.org -Verbosity detailed
Pushing LibGit2.PowerShell.0.2.0.nupkg to 'https://www.nuget.org/api/v2/'...
  PUT https://www.nuget.org/api/v2/
  MethodNotAllowed https://www.nuget.org/api/v2/ 14727ms
NuGet.exe : System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
At line:1 char:1
+ & "F:\Build\LibGit2.PowerShell\packages\Silk\Silk\bin\NuGet.exe" push ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Aggregat...d Not Allowed).:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()
   --- 
End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__16.MoveNext()<---
```

[2]
```
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                              10.32.78.4 -    0 |  173 |  173 |    0 |    0 |   35 |   10 |
|                             10.33.0.161 -   26 |   86 |   64 |    0 |    0 |    0 |    0 |
|                             10.33.0.202 -   26 |   85 |   63 |    0 |    0 |    6 |    0 |
|              por-edge-03.inet.qwest.net -    0 |  173 |  173 |    0 |    1 |   43 |    0 |
|              sea-brdr-02.inet.qwest.net -    0 |  173 |  173 |    4 |    4 |   20 |    4 |
|                            192.16.54.90 -    0 |  173 |  173 |    4 |    4 |   34 |    4 |
|                          93.184.215.200 -    0 |  173 |  173 |    4 |    4 |    6 |    4 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

**Comment by skofman1** [comment]
Please follow the instructions here: https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#push
-Source should be https://www.nuget.org/api/v2/package

**Comment by splatteredbits** [comment]
Thanks.

**Comment by shyamhd** [comment]
@skofman1  I facing issue this issue. I have followed your answer.
I have tried pushing package through HTTP and HTTPS both ways with no success.
Can you please help me regarding this?

**Comment by shyamhd** [comment]
Issue has been resolved after reading this issue https://github.com/NuGet/NuGetGallery/issues/3154
