### ISSUE TITLE
ImportAzureCDNStatistics fails when the same user agent appears in different casings

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3410]
The job failed when in a single file two identical user agents with different casing appeared:
```
Mozilla/5.0 (Linux; U; Android 4.2.2; en-US; TECNO S9 Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 UCBrowser/9.4.1.362 U3/0.8.0 Mobile Safari/533.1
Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; TECNO S9 Build/JDQ39) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 UCBrowser/9.4.1.362 U3/0.8.0 Mobile Safari/533.1

```

Line: https://github.com/NuGet/NuGet.Jobs/blob/master/src/Stats.ImportAzureCdnStatistics/Warehouse.cs#L1065

Exception: An item with the same key has already been added.
Stack trace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Stats.ImportAzureCdnStatistics.Warehouse.<RetrieveUserAgentFacts>d__32.MoveNext() in C:\Nuget\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\Warehouse.cs:line 1065

File: wpc_DB16_20161116_0026.log.gz

**Comment by scottbommarito** [comment]
(The casing issue is `en-US` vs `en-us`.)
