### ISSUE TITLE
nuget delete does not work with V2-feedsnuget

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3440]
@Tasteful commented on [Fri Dec 30 2016](https://github.com/NuGet/Home/issues/4169)

NuGet CLI Version: 3.5.0.1996

I'm using the NuGet.Server 2.11.3 that is working with V2 feeds. When trying to delete a package with `nuget delete` command with what I think is V3 feed url.

In my local test feed I added one package 
```
nuget list -source NugetServerTest -verbosity detailed
NuGet Version: 3.5.0.1996
Using credentials from config. UserName: patric.forsgard
GET http://localhost:41851/NuGet/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm=''&targetFramework=''&includePrerelease=false
Microsoft.Web.Xdt
 2.1.1
 Microsoft Xml Document Transformation (XDT) library. For more info on XDT please visit http://msdn.microsoft.com/en-us
 /library/dd465326.aspx.
 License url: http://go.microsoft.com/fwlink/?LinkId=273778
```

and when I tried to delete the package it looks like the following
```
nuget delete Microsoft.Web.Xdt 2.1.1 -source NugetServerTest -verbosity detai
led
NuGet Version: 3.5.0.1996
WARNING: No API Key was provided and no API Key could be found for 'http://localhost:41851/NuGet/'. To save an API Key for a source use the 'setApiKey' command.
Microsoft.Web.Xdt 2.1.1 will be deleted from the 'http://localhost:41851/NuGet/'. Would you like to continue? (y/N) y
WARNING: Deleting Microsoft.Web.Xdt 2.1.1 from the 'http://localhost:41851/NuGet/'.
  DELETE http://localhost:41851/NuGet/Microsoft.Web.Xdt/2.1.1
  NotFound http://localhost:41851/NuGet/Microsoft.Web.Xdt/2.1.1 123ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<DeletePackageFromServer>b__23_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackageFromServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackage>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Delete>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.DeleteRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.DeleteCommand.<ExecuteCommandAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<DeletePackageFromServer>b__23_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackageFromServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<DeletePackage>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Delete>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.DeleteRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.DeleteCommand.<ExecuteCommandAsync>d__12.MoveNext()<---
```

When I check the XML for the path to the package it is showing `http://localhost:41851/api/v2/package/microsoft.web.xdt/2.1.1`.

Is the delete command using wrong path for removing packages?

(same issue with nuget cli 3.4.4)

---

@joelverhagen commented on [Fri Dec 30 2016](https://github.com/NuGet/Home/issues/4169#issuecomment-269808745)

This is a NuGet.Server issue, not client (nuget.exe). Moving to the server-side repo.

**Comment by joelverhagen** [comment]
`delete` on NuGet.Server is pretty unclear today. The only hint you get (without looking at the code) is the URL mentioned on the NuGet.Server home page for push:

```
nuget.exe push {package file} {api key} -Source http://localhost:48222/api/v2/package
```

You can use this same source URL for deleting.

```
nuget.exe delete {package ID} {package version} -Source http://localhost:48222/api/v2/package
```

I've tested this out for recent versions of NuGet.Server (2.8.6, 2.10.1, 2.11.2, 2.11.3) and nuget.exe (3.3.0, 3.5.0). I would argue though (and I think this is the root cause of your original question) that this is too confusing and hard to discover. I will leave this bug open as a tracking issue for improving the the delete and push experience for NuGet.Server. I'm not sure of the resolution yet but you can use the URLs above as a workaround. 

In the end, I think the behavior of delete and push on NuGet.Server should be similar to NuGet.org, MyGet, VSO, etc.

**Comment by Tasteful** [comment]
I have added `http://localhost:41851/NuGet/` as a package source (with password), that url is working for both fetching packages and pushing new packages to the repository, but not deleting.

The https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/DataServices/Routes.cs.pp have a row for registering the publish for the `/NuGet/` above the registration of listing url.
```
            routes.MapDelegate("CreatePackageNuGet",
                               "nuget",
                               new { httpMethod = new HttpMethodConstraint("PUT") },
                               context => CreatePackageService().CreatePackage(context.HttpContext));
```

after adding the following route the `DELETE` command will work, maybe should be in the https://github.com/NuGet/NuGet.Server/blob/master/src/NuGet.Server/DataServices/Routes.cs.pp as default on the same way as the `PUT`.
```
            routes.MapDelegate("DeletePackageNuGet",
                               "nuget/{packageId}/{version}",
                               new { httpMethod = new HttpMethodConstraint("DELETE") },
                               context => CreatePackageService().DeletePackage(context.HttpContext));
```
