### ISSUE TITLE
Investigate failing dashboard jobs

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#3618]
Some of the dashboard jobs appear to be failing. This is visible in the Task Schedule, NuGetDashboard > Prod0
![image](https://cloud.githubusercontent.com/assets/94054/23566408/97a76e18-0006-11e7-9c81-e4b511cb9eb4.png)

This is int0
![image](https://cloud.githubusercontent.com/assets/94054/23566423/a75cae0e-0006-11e7-9adb-db2345c46ad7.png)

**Comment by joelverhagen** [comment]
V3CatalogMonitoringTask is failing with this:
```
error: ArgumentException: '2' is not a valid version string.
error: Parameter name: value
error:  Stack Trace:    at NuGet.Versioning.NuGetVersion.Parse(String value)
error: at NuGet.Services.Metadata.Catalog.CatalogIndexReader.<>c__DisplayCl
error: ass14.<GetEntries>b__13(Uri uri)
error: at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachW
error: orker>b__0(Int32 i)
error: at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorke
error: r>b__1()
error:    at System.Threading.Tasks.Task.InnerInvoke()
error:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
error: at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfRe
error: plicating>b__0(Object )
```

**Comment by joelverhagen** [comment]
`V3CatalogMonitoringTask` loads the entire catalog into memory. This either needs to change or we need to remove the job entirely.

**Comment by joelverhagen** [comment]
Fixed manually. Deployment script is updated with this PR: https://github.com/NuGet/NuGetGallery/issues/3618.
