### ISSUE TITLE
Scenario fails: nuget.exe install latest a package that only has SemVer 2.0.0 versions

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#3917]
Installing semver2 package w/o specifying version fails. Should it be checking the semver2 registration from the feed URL?

```
> D:\tools\NuGetClients\v4.1.0\NuGet.exe install -Source http://api.dev.nugettest.org/v3-index/index.json jver.bugbash.metadata -Verbosity detailed
NuGet Version: 4.1.0.2450
Feeds used:
  http://api.dev.nugettest.org/v3-index/index.json

  GET https://az635243.vo.msecnd.net/v3-registration2-gz/jver.bugbash.metadata/index.json
  NotFound https://az635243.vo.msecnd.net/v3-registration2-gz/jver.bugbash.metadata/index.json 352ms
System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Unable to find pack
age 'jver.bugbash.metadata'
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) NuGet.CommandLine.CommandLineException: Unable to find package 'jver.bugbash.metadata'
   at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()<---
```

**Comment by skofman1** [comment]
@xavierdecoster , was this fixed?

**Comment by chenriksson** [comment]
This was for the following scenario... but behavior is by design. Discussed w/ @joelverhagen that 4.1 client should fail to install latest semver2, but will download specific version. We can close.

nuget.exe install latest a package that only has SemVer 2.0.0 versions 
chenriks: NuGet.exe 4.1 (Bug #3917)
