### ISSUE TITLE
Build fail - Server 2016

### ISSUE THREAD

**Issue by Chirishman** [NuGet/NuGetGallery#4026]
Build fail in step three following the readme on a fresh install of Server 2016. PSVersion 5.1.14393.576

```
PS C:\Code\NuGetGallery> .\build
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399c
e85f4ff20b
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
Queue-Build.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
common.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
init.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
sign.targets
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/tools?ref=37ff6e758c38b3f513af39f881399c
e85f4ff20b
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/tools/7zip?ref=37ff6e758c38b3f513af39f88
1399ce85f4ff20b
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/tools/
7zip/7-zip.chm
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/tools/
7zip/7za.exe




[13:20:53 +0]   ============================================================
[13:20:53 +0]   Build #98656 started at 05/30/2017 17:20:53
[13:20:53 +0]   [BEGIN] Getting private build tools
[13:20:53 +0]   No private build tools are configured. Use the 'PRIVATE_BUILD_TOOLS_REPO' and 'PRIVATE_BUILD_TOOLS_COMMI
T' environment variables.
[13:20:53 +0]   [DONE +0:00] Getting private build tools
[13:20:53 +0]   [BEGIN] Cleaning test results
[13:20:53 +0]   Cleaning test results
[13:20:53 +0]   [DONE +0:00] Cleaning test results
[13:20:53 +0]   [BEGIN] Installing NuGet.exe
[13:20:53 +0]   Downloading VSTS credential provider
[13:21:05 +12]  Downloading latest prerelease of nuget.exe
[13:21:14 +9]   [DONE +0:20] Installing NuGet.exe
WARNING: [13:21:14 +0] [SKIP] Clearing package cache
[13:21:14 +0]   [BEGIN] Clearing artifacts
[13:21:14 +0]   Clearing the Artifacts folder
[13:21:14 +0]   [DONE +0:00] Clearing artifacts
[13:21:14 +0]   [BEGIN] Restoring solution packages
[13:21:14 +0]   Installing packages @"C:\Code\NuGetGallery\.nuget"
[13:21:14 +0]   C:\Code\NuGetGallery\.nuget\nuget.exe install C:\Code\NuGetGallery\.nuget\packages.config -verbosity qui
et -NonInteractive -ExcludeVersion -OutputDirectory C:\Code\NuGetGallery\packages
[13:21:15 +1]   [DONE +0:01] Restoring solution packages
[13:21:15 +0]   [BEGIN] Set version metadata in AssemblyInfo.cs


    Directory: C:\Code\NuGetGallery\src\NuGetGallery\Properties


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        5/30/2017   1:21 PM              0 AssemblyInfo.g.cs
[13:21:15 +0]   Getting version info in @"C:\Code\NuGetGallery\src\NuGetGallery\Properties\AssemblyInfo.g.cs"
[13:21:15 +0]   [assembly: AssemblyVersion("1.0.0")]
[13:21:15 +0]   [assembly: AssemblyInformationalVersion("1.0.0-master")]
[13:21:15 +0]   [assembly: AssemblyMetadata("Branch", "master")]
[13:21:15 +0]   [assembly: AssemblyMetadata("CommitId", "f8c92462")]
[13:21:15 +0]   [assembly: AssemblyMetadata("BuildDateUtc", "05/30/2017 17:21:15 +00:00")]


    Directory: C:\Code\NuGetGallery\src\NuGetGallery.Core\Properties


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        5/30/2017   1:21 PM              0 AssemblyInfo.g.cs
[13:21:15 +0]   Getting version info in @"C:\Code\NuGetGallery\src\NuGetGallery.Core\Properties\AssemblyInfo.g.cs"
[13:21:15 +0]   [assembly: AssemblyVersion("1.0.0")]
[13:21:15 +0]   [assembly: AssemblyInformationalVersion("1.0.0-master")]
[13:21:15 +0]   [assembly: AssemblyMetadata("Branch", "master")]
[13:21:15 +0]   [assembly: AssemblyMetadata("CommitId", "f8c92462")]
[13:21:15 +0]   [assembly: AssemblyMetadata("BuildDateUtc", "05/30/2017 17:21:15 +00:00")]
[13:21:15 +0]   [DONE +0:00] Set version metadata in AssemblyInfo.cs
[13:21:15 +0]   [BEGIN] Building solution
Error-Log : [13:21:17 +2]       [FAILED +0:01] Building solution
At C:\Code\NuGetGallery\build\common.ps1:164 char:21
+ ...             Error-Log "[FAILED +$(Format-ElapsedTime $sw.Elapsed)] $B ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Error-Log

BUILD FAILED: Exception calling "GetInstancePaths" with "0" argument(s): "Retrieving the COM class factory for component
 with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exc
eption from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
ERROR DETAILS:
System.Management.Automation.MethodInvocationException: Exception calling "GetInstancePaths" with "0" argument(s): "Retr
ieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following
 error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))." ---> System.Runtime.I
nteropServices.COMException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9F
A36D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLAS
SNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCache
d, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark
& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NuGet.Services.Build.VisualStudioSetupConfigurationHelper.GetInstancePaths()
   at CallSite.Target(Closure , CallSite , Type )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProces
s)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
```

**Comment by skofman1** [comment]
@scottbommarito ?

**Comment by scottbommarito** [comment]
Basically, it's downloading `NuGet.Services.Build` and then adding the type to the PowerShell script. I'm not sure why it's failing. We were seeing this on our hosted agents but not our build agents.

I would check that
1 - The package was downloaded successfully (check the existence of `NuGet.Services.Build` in `build/packages`).
2 - The latest version of VS is installed.
3 - The latest version of PowerShell is installed.

**Comment by rupendra-sharma** [comment]
Hi, just wondering if this is fixed? I am using the full download of master branch and experiencing the same issue.
I am using VS 2015 on Windows 10. .Net v 4.6.1
Stack trace of the error is as following:
PS F:\Study\NuGet local gallary\NuGetGallery-master> .\build
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399c
e85f4ff20b
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
Queue-Build.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
common.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
init.ps1
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/
sign.targets
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/tools?ref=37ff6e758c38b3f513af39f881399c
e85f4ff20b
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/tools/7zip?ref=37ff6e758c38b3f513af39f88
1399ce85f4ff20b
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/tools/
7zip/7-zip.chm
Downloading file at https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/tools/
7zip/7za.exe




[10:31:43 +0]   ============================================================
[10:31:43 +0]   Build #115326 started at 07/27/2017 05:01:43
[10:31:43 +0]   [BEGIN] Getting private build tools
[10:31:43 +0]   No private build tools are configured. Use the 'PRIVATE_BUILD_TOOLS_REPO' and 'PRIVATE_BUILD_TOOLS_COMMI
T' environment variables.
[10:31:43 +0]   [DONE +0:00] Getting private build tools
[10:31:43 +0]   [BEGIN] Cleaning test results
[10:31:43 +0]   Cleaning test results
[10:31:43 +0]   [DONE +0:00] Cleaning test results
[10:31:43 +0]   [BEGIN] Installing NuGet.exe
[10:31:43 +0]   Downloading VSTS credential provider
[10:32:25 +42]  Downloading latest prerelease of nuget.exe
[10:32:34 +10]  [DONE +1:51] Installing NuGet.exe
WARNING: [10:32:34 +0] [SKIP] Clearing package cache
[10:32:34 +0]   [BEGIN] Clearing artifacts
[10:32:34 +0]   Clearing the Artifacts folder
[10:32:34 +0]   [DONE +0:00] Clearing artifacts
[10:32:34 +0]   [BEGIN] Restoring solution packages
[10:32:34 +0]   Installing packages @"F:\Study\NuGet local gallary\NuGetGallery-master\.nuget"
[10:32:34 +0]   F:\Study\NuGet local gallary\NuGetGallery-master\.nuget\nuget.exe install F:\Study\NuGet local gallary\N
uGetGallery-master\.nuget\packages.config -verbosity quiet -NonInteractive -ExcludeVersion -OutputDirectory F:\Study\NuG
et local gallary\NuGetGallery-master\packages
[10:32:35 +1]   [DONE +0:00] Restoring solution packages
[10:32:35 +0]   [BEGIN] Set version metadata in AssemblyInfo.cs


    Directory: F:\Study\NuGet local gallary\NuGetGallery-master\src\NuGetGallery\Properties


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        7/27/2017  10:32 AM              0 AssemblyInfo.g.cs
[10:32:35 +0]   Getting version info in @"F:\Study\NuGet local gallary\NuGetGallery-master\src\NuGetGallery\Properties\A
ssemblyInfo.g.cs"
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[10:32:35 +0]   [assembly: AssemblyVersion("1.0.0")]
[10:32:35 +0]   [assembly: AssemblyInformationalVersion("1.0.0-")]
[10:32:35 +0]   [assembly: AssemblyMetadata("Branch", "")]
[10:32:35 +0]   [assembly: AssemblyMetadata("CommitId", "")]
[10:32:35 +0]   [assembly: AssemblyMetadata("BuildDateUtc", "07/27/2017 05:02:35 +00:00")]


    Directory: F:\Study\NuGet local gallary\NuGetGallery-master\src\NuGetGallery.Core\Properties


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        7/27/2017  10:32 AM              0 AssemblyInfo.g.cs
[10:32:35 +0]   Getting version info in @"F:\Study\NuGet local gallary\NuGetGallery-master\src\NuGetGallery.Core\Propert
ies\AssemblyInfo.g.cs"
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
[10:32:36 +0]   [assembly: AssemblyVersion("1.0.0")]
[10:32:36 +0]   [assembly: AssemblyInformationalVersion("1.0.0-")]
[10:32:36 +0]   [assembly: AssemblyMetadata("Branch", "")]
[10:32:36 +0]   [assembly: AssemblyMetadata("CommitId", "")]
[10:32:36 +0]   [assembly: AssemblyMetadata("BuildDateUtc", "07/27/2017 05:02:36 +00:00")]
[10:32:36 +0]   [DONE +0:00] Set version metadata in AssemblyInfo.cs
[10:32:36 +0]   [BEGIN] Building solution
[10:32:36 +1]   Installing and configuring NuGet.Services.Build
Error-Log : [10:32:37 +0]    [FAILED +0:01] Building solution
At F:\Study\NuGet local gallary\NuGetGallery-master\build\common.ps1:164 char:21
+ ...             Error-Log "[FAILED +$(Format-ElapsedTime $sw.Elapsed)] $B ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Error-Log

BUILD FAILED: Exception calling "GetInstancePaths" with "0" argument(s): "Retrieving the COM class factory for component
 with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Class not registered (Exc
eption from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
ERROR DETAILS:
System.Management.Automation.MethodInvocationException: Exception calling "GetInstancePaths" with "0" argument(s): "Retr
ieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following
 error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))." ---> System.Runtime.I
nteropServices.COMException: Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9F
A36D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLAS
SNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCache
d, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark
& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at NuGet.Services.Build.VisualStudioSetupConfigurationHelper.GetInstancePaths()
   at CallSite.Target(Closure , CallSite , Type )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProces
s)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()

**Comment by scottbommarito** [comment]
@rupendra-sharma 

We no longer support VS 2015 for building the gallery. Please upgrade to VS 2017 and try again. If it fails in the same way, I suggest checking that
1 - The build package was downloaded successfully (check the existence of `NuGet.Services.Build` in `build/packages`).
2 - The latest version of VS is successfully installed.
3 - The latest version of PowerShell is installed.
