### ISSUE TITLE
biuld.ps1 errors

### ISSUE THREAD

**Issue by user1025** [NuGet/NuGetGallery#4262]
at my test environment getting following errors while build process:

> PS C:\code\NuGetGallery> .\build
> 
> 
> BUILD FAILED: The term 'Trace-Log' is not recognized as the name of a cmdlet, function, script file, or operable program
> . Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> ERROR DETAILS:
> System.Management.Automation.CommandNotFoundException: The term 'Trace-Log' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
>    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
>    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
>    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
>    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
>    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
>    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

use windows 7 PS1 (just installed), and following instuction:

> 1.Prerequisites:
> i.Visual Studio 2017 - Install the following  Workloads : 
>    ◾ASP.NET and web development
>    ◾Azure development
> ii.PowerShell 4.0
> 
> 
> 2.Clone it!
>     PS C:\Code> git clone https://github.com/NuGet/NuGetGallery.git 
> 
> 
> 3.Build it!
>     PS C:\Code> cd NuGetGallery
>     PS C:\Code\NuGetGallery> .\build

common difference - at my OS installed PowerShell 5.0, Visual Studio 2017 Community Edition

where i can find cmdlets:  Trace-Log, Invoke-BuildStep, Get-BuildNumber, Install-PrivateBuildTools, Clean-Tests etc. ?
or, may be i need to build another project before i can build NuGetGallery? (no such info in README.md)

**Comment by user1025** [comment]
it was not enoth interbet access.
file .\build\init.ps1 solve my problem.
