### ISSUE TITLE
[Redesign] Stats page crashes when there are no client versions

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4464]
Repro: https://preview.int.nugettest.org/stats

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at ASP._Page_Views_Statistics_Index_cshtml.Execute() in e:\sitesroot\0\Views\Statistics\Index.cshtml:line 110
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

Code:
```csharp
var widthOffsetPercent = 100.0 - chartFullWidthInPercent;
var index = 0;
var gapPercent = .1;
var max = showVersions.Max(e => e.Downloads) * 1.0;
```
https://github.com/NuGet/NuGetGallery/blob/d92ddb311a2e473779228e465b6a884587b80af1/src/NuGetGallery/Views/Statistics/Index.cshtml#L110

**Comment by joelverhagen** [comment]
Merged but not yet deployed.
