### ISSUE TITLE
Trailing space (%20) on package ID in CDN logs causes log file to be rejected

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#4802]
The following CDN path (not a full URL to avoid more instances of this occurring) causes a CDN log file to fail parsing:
```
/v3-flatcontainer/microsoft.applicationinsights.dependencycollector%20/2.4.1/microsoft.applicationinsights.dependencycollector%20.2.4.1.nupkg
```

Notice the `%20` at the end of the ID. This request normally results in a 404 (which is ignore) but in this particular case a HTTP 504 was returned, presumably due to an intermittent Azure Blob Storage error.

The following exception is thrown:
```
Unable to process "https://REDACTED.blob.core.windows.net/nuget-cdnlogs-raw/wpc_REDACTED_20171003_0043.log.gz"
System.Data.SqlClient.SqlException (0x80131904): Violation of UNIQUE KEY constraint 'UQ__#A0F4246__A16B9C09C7200580'. Cannot insert duplicate key in object 'dbo.@packages'. The duplicate key value is (microsoft.applicationinsights.dependencycollector , 2.4.1).
The data for table-valued parameter "@packages" doesn't conform to the table type of the parameter. SQL Server error is: 3602, state: 30
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stats.ImportAzureCdnStatistics.Warehouse.<RetrievePackageDimensions>d__27.MoveNext() in C:\src\git\github.com\NuGet\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\Warehouse.cs:line 723
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stats.ImportAzureCdnStatistics.Warehouse.<GetDimension>d__23`1.MoveNext() in C:\src\git\github.com\NuGet\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\Warehouse.cs:line 585
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stats.ImportAzureCdnStatistics.Warehouse.<CreateAsync>d__15.MoveNext() in C:\src\git\github.com\NuGet\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\Warehouse.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stats.ImportAzureCdnStatistics.LogFileProcessor.<ProcessPackageStatisticsInLogFileAsync>d__6.MoveNext() in C:\src\git\github.com\NuGet\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\LogFileProcessor.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Stats.ImportAzureCdnStatistics.LogFileProcessor.<ProcessLogFileAsync>d__4.MoveNext() in C:\src\git\github.com\NuGet\NuGet.Jobs\src\Stats.ImportAzureCdnStatistics\LogFileProcessor.cs:line 54
```

**Comment by joelverhagen** [comment]
Could be related to a client issue: https://github.com/NuGet/Home/issues/5984
