### ISSUE TITLE
Cancel of package upload relies on parser error to clear the page

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#4806]
Repo:
- Open the Upload page
- F12, add breakpoint at async-file-upload->handleErrors (line 165)
- Upload a package, which sends POST to /packages/manage/cancel-upload
- Breakpoint in handleErrors should be hit

resultCodeString = "parsererror".

Stack is:
    "SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at jQuery.parseJSON (https://localhost/Scripts/gallery/jquery-1.12.4.js:9011:22)
    at ajaxConvert (https://localhost/Scripts/gallery/jquery-1.12.4.js:9335:19)
    at done (https://localhost/Scripts/gallery/jquery-1.12.4.js:9789:15)
    at XMLHttpRequest.callback (https://localhost/Scripts/gallery/jquery-1.12.4.js:10311:8)"

**Comment by chenriksson** [comment]
Need to see if this still repros
