### ISSUE TITLE
[BugBash] 500 errors when cancel on initial auth flow

### ISSUE THREAD

**Issue by chenriksson** [NuGet/NuGetGallery#5451]
Scenario 9, per @joelverhagen 

Hitting cancel during initial auth...

Can you also investigate possible 500 here...

Scenario 2, per @skofman1 (Issue 2)

After I finished the linking, and got back to home page, clicked "back" a few times and got a 500...

**Comment by joelverhagen** [comment]
I can repro this in INT with my jver account.

**Comment by scottbommarito** [comment]
```
System.InvalidOperationException: The 'MicrosoftAccount' authentication provider is disabled and cannot be used to authenticate

   at NuGetGallery.Authentication.AuthenticationService.Challenge(String providerName, String redirectUrl) in C:\vsts-agent\_work\12\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Authentication\AuthenticationService.cs:line 486
   at NuGetGallery.AuthenticationController.AuthenticateAndLinkExternal(String returnUrl, String provider) in C:\vsts-agent\_work\12\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Controllers\AuthenticationController.cs:line 371
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```
