### ISSUE TITLE
Hitting disabled external provider route returns 500

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5484]
https://dev.nugettest.org/users/account/authenticate/MicrosoftAccount

This produces the following exception

```
System.InvalidOperationException: The 'MicrosoftAccount' authentication provider is disabled and cannot be used to authenticate

   at NuGetGallery.Authentication.AuthenticationService.Challenge(String providerName, String redirectUrl) in C:\vsts-agent\_work\12\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Authentication\AuthenticationService.cs:line 486
   at NuGetGallery.AuthenticationController.AuthenticateAndLinkExternal(String returnUrl, String provider) in C:\vsts-agent\_work\12\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Controllers\AuthenticationController.cs:line 363
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

We should handle this more gracefully.

/cc @shishirx34

**Comment by shishirx34** [comment]
Agree, but Ideally I think this route should never be hit from our code path, the user would(should?) never end up on a provider that is not enabled.

**Comment by skofman1** [comment]
@shishirx34 , is this the issue we are seeing when bots hit this URL?

**Comment by shishirx34** [comment]
Yes, I have the fix with the next PR I am about to send out.
