### ISSUE TITLE
In build.ps1 scripts that fetch from ServerCommon, set SSL protocols

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#5551]
A lot of machines default to SSL 3.0 and TLS 1.0, which is not compatible with GitHub.

```
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

Repositories:
- [x] NuGetGallery
- [x] NuGet.Jobs
- [x] NuGet.Server
- [x] NuGet.Services.Metadata
- [x] NuGet.Services.EndToEnd

**Comment by joelverhagen** [comment]
Workaround is to run this on your machine:
```
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
```
