### ISSUE TITLE
403 Forbidden Error on PUT Request

### ISSUE THREAD

**Issue by talaniz** [NuGet/NuGetGallery#5553]
Hello, I've followed the instructions from Microsoft on setting this up [here](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server). When I run locally in debug mode, I'm getting a consistent 403 Forbidden error--

`C:\Users\talaniz>nuget push C:\bin\Octopus\DiagnosticsPackage.6.1.5.0.nupkg -ApiKey test123 -Source http://localhost:53405/nuget
Pushing DiagnosticsPackage.6.1.5.0.nupkg to 'http://localhost:53405/nuget'...
  PUT http://localhost:53405/nuget/
  Forbidden http://localhost:53405/nuget/ 803ms
Response status code does not indicate success: 403 (Forbidden).`

I'm using nuget client v.3.5.0.1996, the Verbosity flag tracestack was not helpful but I wanted to include it here--

`C:\Users\talaniz>nuget push C:\bin\Octopus\DiagnosticsPackage.6.1.5.0.nupkg -ApiKey test123 -Source http://localhost:53405/nuget -Verbosity detailed
NuGet Version: 3.5.0.1996
Pushing DiagnosticsPackage.6.1.5.0.nupkg to 'http://localhost:53405/nuget'...
  PUT http://localhost:53405/nuget/
  Forbidden http://localhost:53405/nuget/ 444ms
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14 1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14 1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()<---`

I am also attaching my webconfig--
[Webconfig.zip](https://github.com/NuGet/NuGetGallery/files/1765040/Webconfig.zip)

A few changes that I made to note--
- RequireApiKey was set to true (I'm including this flag in my call when I put)
- Packages Path was updated to C:\NugetPackages (I created it in advance)
- A "Feeds_AddPackage" tag was added with the value attribute set to "true"
- I have tried commenting out and adding in the following lines with the same effect:

```<!-- <remove name="ExtensionlessUrlHandler-Integrated-4.0" />-->
 <!-- <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,PUT,DEBUG" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />-->```

I see I'm logged in as an anonymous user in my requests, but assumed the API key would allow me to auth. Can someone please take a look and advise if there's something obvious I've maybe missed? Apologies for the messy formatting on the stack, I couldn't get the code formatting to work in multi-line without it turning everything into code formatting unless I switched to single line :(

**Comment by skofman1** [comment]
@talaniz , which version of NuGet.Server are you using? I followed the instructions here: https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server with the latest version, and it worked smoothly. Also, I couldn't find a setting called "Feeds_AddPackage", can you provide more details?

**Comment by talaniz** [comment]
@skofman1 Apologies for the delay. I wiped the installation and retried the steps again, this time I was able to push and pull successfully. I'm not sure what happened, but it must have been a user error. Thanks for following up.

Closing out.
