### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by chipitsine** [NuGet/NuGetGallery#5575]
by default powershell uses SSL3 and TLS1 in ```[Net.ServicePointManager]::SecurityProtocol```

recently api.github.com removed support for TLS1 (only TLS1.2 left), so build fails with

```
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399ce85f4ff20b
VERBOSE: GET https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399ce85f4ff20b with 0-byte 
payload
BUILD FAILED: The underlying connection was closed: An unexpected error occurred on a send.
ERROR DETAILS:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

after I added

```
[Net.ServicePointManager]::SecurityProtocol += [Net.SecurityProtocolType]::Tls12
```

to build.ps1 - build is fixed

should we add it permanently ? or there's better solution ?

**Comment by edyoung** [comment]
The same fix is in the dev branch and will be merged to master soon. #5551

**Comment by joelverhagen** [comment]
Thanks @edyoung. Yup, this is a duplicate of https://github.com/NuGet/NuGetGallery/issues/5551.

> Workaround is to run this on your machine:
> ```
> Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
> Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
> ```
