### ISSUE TITLE
Issue Running .\build command

### ISSUE THREAD

**Issue by ryanvgates** [NuGet/NuGetGallery#5579]
I'm following the instructions from the [readme ](https://github.com/NuGet/NuGetGallery#build-and-run-the-gallery-in-arbitrary-number-easy-steps)to setup the nuget gallery. I get the following error when I run in it the command prompt as Administrator.

```
C:\Users\---\AppData\Local\lxss\home\---\github\nuget\NuGetGallery>.\build

PowerShell.exe -NoProfile -ExecutionPolicy ByPass ".\buildandtest.ps1 -Configuration 'Release' -Verbose"
VERBOSE: GET
https://raw.githubusercontent.com/NuGet/ServerCommon/37ff6e758c38b3f513af39f881399ce85f4ff20b/build/init.ps1 with
0-byte payload
VERBOSE: received 1655-byte response of content type text/plain; charset=utf-8
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399ce85f4ff20b
VERBOSE: GET
https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399ce85f4ff20b with 0-byte
 payload
BUILD FAILED: The request was aborted: Could not create SSL/TLS secure channel.
ERROR DETAILS:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()

BUILD FAILED: The term 'C:\Users\---\AppData\Local\lxss\home\---\github\nuget\NuGetGallery\build\common.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR DETAILS:
System.Management.Automation.CommandNotFoundException: The term 'C:\Users\---\AppData\Local\lxss\home\---\github\nuget\NuGetGallery\build\common.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

I get the following issue when I run it in powershell as Administrator.

```
PS C:\Users\---\AppData\Local\lxss\home\---\github\nuget\NuGetGallery> .\build
Downloading files from https://api.github.com/repos/NuGet/ServerCommon/contents/build?ref=37ff6e758c38b3f513af39f881399ce85f4ff20b
BUILD FAILED: The request was aborted: Could not create SSL/TLS secure channel.
ERROR DETAILS:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```

How can I build the project successfully?

**Comment by skofman1** [comment]
@ryanvgates , GitHub recently stopped supporting TLS 1.0 in it's APIs, this is why the build script is failing.
We fixed the issue in our DEV branch: https://github.com/NuGet/NuGetGallery/commit/04c982888b1af2ced6a2187c5bf889b5c879421f

You can use this branch instead of master.

**Comment by ryanvgates** [comment]
@skofman1 Once I ran it on the DEV branch it worked. Thank you for your help.
