### ISSUE TITLE
Arg Null exception after deleting a package that has an ownership request.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/NuGetGallery#5940]
Steps to repro
Publish a package 
Create an ownership request for it
Delete the package
Open the Account Settings -> Manage Packages 

Result 
System.ArgumentNullException
Value cannot be null. Parameter name: package

System.ArgumentNullException: Value cannot be null.
Parameter name: package
   at NuGetGallery.PackageViewModel..ctor(Package package) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\PackageViewModel.cs:line 19
   at NuGetGallery.ListPackageItemViewModel..ctor(Package package, User currentUser) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\ListPackageItemViewModel.cs:line 19
   at NuGetGallery.OwnerRequestsListItemViewModel..ctor(PackageOwnerRequest request, IPackageService packageService, User currentUser) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\OwnerRequestsListItemViewModel.cs:line 13
   at NuGetGallery.OwnerRequestsListViewModel.<>c__DisplayClass0_0.<.ctor>b__0(PackageOwnerRequest r) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\OwnerRequestsListViewModel.cs:line 13
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NuGetGallery.OwnerRequestsListViewModel..ctor(IEnumerable`1 requests, User currentUser, IPackageService packageService) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\OwnerRequestsListViewModel.cs:line 13
   at NuGetGallery.OwnerRequestsViewModel..ctor(IEnumerable`1 received, IEnumerable`1 sent, User currentUser, IPackageService packageService) in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\ViewModels\OwnerRequestsViewModel.cs:line 27
   at NuGetGallery.UsersController.Packages() in C:\vsts-agent\_work\31\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Controllers\UsersController.cs:line 469
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by ryuyu** [comment]
I was able to repro this for a single instant, after which it went away on its own.
It appears this mayyyyy be caused by a race condition in which the packages are enumerated, the package is deleted, and then the requests for the package datas are made.
Ownership request appear to properly disappear with the package deletion now.

We can watch the logs and revisit this if we see this occurring again.
