### ISSUE TITLE
BUILD FAILED: The variable '$FilePath' cannot be retrieved because it has not been set.

### ISSUE THREAD

**Issue by RichardD2** [NuGet/NuGetGallery#6334]
I'm trying to install this project, and falling at the first hurdle.

Following the instructions from the project home page, I get as far as:

3. Build it!
```
PS C:\Code> cd NuGetGallery
PS C:\Code\NuGetGallery> .\build
```
and the script returns an error:

```
PS E:\...\NuGetGallery> .\build


    Directory: E:\...\NuGetGallery


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       21/08/2018  04:21 PM                build
BUILD FAILED: The variable '$FilePath' cannot be retrieved because it has not been set.
ERROR DETAILS:
System.Management.Automation.RuntimeException: The variable '$FilePath' cannot be retrieved because it has not been set.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
```

Have I missed something obvious?

**Comment by scottbommarito** [comment]
This is a bug in https://github.com/NuGet/ServerCommon/blob/master/build/init.ps1
It was fortunately a very easy fix, so I've already updated the code.

Our build system has strict mode off, so the code doesn't throw an exception for us.
The code just so happened to work with strict mode off because of some coincidences with how PowerShell works.

For now:
1. Turn off strict mode.
2. Run `.\build.ps1 -BuildBranch 9f570166c49e93a911e54505a8041f3a123e69b1`

I have verified that with this fix the gallery now builds correctly in strict mode.
I will be updating the gallery so that you don't have to pass in the parameter directly for strict mode to work.
