### ISSUE TITLE
NuGet.Server: Better messages when package won't push

### ISSUE THREAD

**Issue by StuffOfInterest** [NuGet/NuGetGallery#6543]
I'm operating a NuGet server using the latest NuGet.Server package in a disconnected network.  I've run across one Microsoft package that refuses to upload to the server.  I've tried both `nuget push` and dropping the package file in the correct folder.

When trying to do a NuGet push, the following results occur:

```
P:\CPM-Publish>nuget.exe push queue\*.nupkg -Source http://(myserver)/nuget -ApiKey (mykey) -Verbosity Normal
Pushing microsoft.aspnetcore.identity.ui.2.1.3.nupkg to 'http://(myserver)/nuget'...
  PUT http://(myserver)/nuget/
  NotAcceptable http://(myserver)/nuget/ 1552ms
Response status code does not indicate success: 406 (Not Acceptable).
```

Running with detailed verbosity provides no more useful detail.

Nothing was recorded in the Application event log.

I'm not sure why this one Microsoft package refuses to load but it would be helpful if the NuGet.Server engine would either report back a more detailed error message to the client or log a more detailed message in the event log.

**Comment by chenriksson** [comment]
Hi @StuffOfInterest, have you tried the solutions in #5084?
- Ensure AppPool user has write permissions to the Packages directory
- Remove duplicate tag
- Set allowOverrideExistingPackageOnPush to true

If you are seeing a different issue, could you provide the following to assist?
- NuGet.Server package version
- Client version used to push
- Which package you're trying to upload (downloaded from NuGet.org?)
- Fiddler trace of the push request

**Comment by StuffOfInterest** [comment]
@chenriksson, thanks for responding.

I took a look at #5084, but the changes listed toward the end did not help.

The app pool has full permissions to the package folder.  I have several hundred packages in there already (done with both nuget push and dropping files in) so permissions should have been OK all along.

Duplicate tag has to be removed just to get the server running in the beginning.  It has been running for a couple of months.

Override existing has been enabled all along as it was easier than trying to de-dup the packages before uploading them.

NuGet.Server version is 3.1.2, the current one available from nuget.org.

Nuget.exe version number is 4.4.1.4656.

Package I'm trying to upload is "microsoft.aspnetcore.identity.ui.2.1.3.nupkg".  It was downloaded form nuget.org.  I've also tried a couple of slightly lower version numbers of that package with the same result.

Headers captured from fiddler.  Host name has been masked.  Request body trimmed after the first few bytes.

```
PUT http://xxxxxxxx:8080/nuget/ HTTP/1.1
X-NuGet-ApiKey: ConcordeKey
user-agent: NuGet Command Line/4.4.1 (Microsoft Windows NT 6.2.9200.0)
X-NuGet-Client-Version: 4.4.1
Accept-Language: en-US
Content-Type: multipart/form-data; boundary="970e4bd0-8ef1-4357-aa61-0d84820ff219"
Accept-Encoding: gzip, deflate
Authorization: Negotiate YIIHRgYGKwYBBQUCoII(continues along for quite a while)
Host:xxxxxxxx:8080
Expect: 100-continue
Content-Length: 733112

--970e4bd0-8ef1-4357-aa61-0d84820ff219
Content-Type: application/octet-stream
Content-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8''package.nupkg

PK    #  L|?Ӹ  	  A% 7   lib/netstandard2.0/Microsoft.AspNetCore.Identity.UI.dll }	
```
There was no response body, just the 406 response code.

Hope this helps.  Thanks.

**Comment by chenriksson** [comment]
@StuffOfInterest I was able to repro the 406 (NotAcceptable) on that package, and captured the following exception in the debugger:

```
iisexpress.exe Error: 0 : System.ArgumentException: Part URI cannot start with two forward slashes.
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ProcessOverrideTagAttributes(XmlTextReader reader)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper.ParseContentTypesFile(ZipFileInfoCollection zipFiles)
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath, IFileSystem expandedFileSystem)
   at NuGet.Server.Core.PackageFactory.Open(String fullPackagePath)
   at NuGet.Server.V2.Controllers.NuGetODataController.<UploadPackage>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

As a workaround, you can try opening the nupkg (7-zip), and modifying the following line of `[Content_Types].xml` to only have a single leading '/'.

```
<Override ContentType="application/octet" PartName="//THIRD-PARTY-NOTICES"/>
```

**Comment by JJoe2** [comment]
Regarding "better messages", I see that NuGet.Server already has a class `TraceExceptionLogger` that logs the exception that would have helped with troubleshooting this problem to `System.Diagnostics.Trace`.  

So it's just a question of adding Trace Listeners to web.config.
