### ISSUE TITLE
MessageService implementations throw when passed an email with no recipients

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#6632]
[`EmailRecipients.GetAllOwners` and `EmailRecipients.GetOwnersSubscribedToPackagePushedNotifications`](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Messaging.Email/EmailRecipients.cs) can return an empty `List<MailAddress>`. [Several `IEmailBuilder`s use these functions to determine `IEmailRecipients.To`.](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Messaging.Email/Messages/PackageAddedMessage.cs#L45) This causes an exception to be thrown [when creating an `EmailMessageData`](https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Messaging/EmailMessageData.cs#L53).

This is due to a faulty comparison in https://github.com/NuGet/ServerCommon/blob/master/src/NuGet.Services.Messaging.Email/AsynchronousEmailMessageService.cs#L45.

We encountered this happening [in the orchestrator](https://github.com/NuGet/NuGetGallery/issues/6631) and the gallery.

**Comment by scottbommarito** [comment]
One of many possible steps to reproduce:

1) Go to Account Settings
2) Turn off "Users can contact you" and "Receiving package push notifications"
3) Go to the manage package owners page for a package only you own
4) Attempt to add another user as owner of the package

```
System.ArgumentException: The parameter 'to' cannot be an empty string.
Parameter name: to
   at System.Net.Mail.MailMessage..ctor(String from, String to)
   at NuGetGallery.Infrastructure.Mail.BackgroundMarkdownMessageService.CloneMessage(MailMessage mailMessage) in E:\A\_work\188\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Infrastructure\Mail\BackgroundMarkdownMessageService.cs:line 77
   at NuGetGallery.Infrastructure.Mail.BackgroundMarkdownMessageService.SendMessageInternalAsync(MailMessage mailMessage) in E:\A\_work\188\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Infrastructure\Mail\BackgroundMarkdownMessageService.cs:line 42
   at NuGetGallery.Infrastructure.Mail.CoreMarkdownMessageService.<SendMessageAsync>d__10.MoveNext() in E:\A\_work\188\s\src\Gallery\submodules\Gallery\src\NuGetGallery.Core\Infrastructure\Mail\CoreMarkdownMessageService.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetGallery.JsonApiController.<AddPackageOwner>d__8.MoveNext() in E:\A\_work\188\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Controllers\JsonApiController.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by scottbommarito** [comment]
Deployment tracked by https://github.com/NuGet/Engineering/issues/1905
