### ISSUE TITLE
Attempting to delete last owner of a package (org) returns 500

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6683]
![image](https://user-images.githubusercontent.com/94054/48654348-06fcf080-e9c1-11e8-8fdc-668dc7943d61.png)

Then I click delete:

![image](https://user-images.githubusercontent.com/94054/48654359-14b27600-e9c1-11e8-8b71-1e53c45f0ff8.png)

Exception in ELMAH:

```
System.InvalidOperationException: You can't remove the only owner from a package.
   at NuGetGallery.JsonApiController.<RemovePackageOwner>d__9.MoveNext() in E:\A\_work\172\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Controllers\JsonApiController.cs:line 229
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by joelverhagen** [comment]
This happened on DEV environment.
