### ISSUE TITLE
Deleting organization with one co-owned package fails

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#6684]
![image](https://user-images.githubusercontent.com/94054/48654412-64913d00-e9c1-11e8-9dde-f86ca5db16ed.png)

```
System.InvalidOperationException: Deleting user 'jverorg' will make package 'System.Rido' an orphan, but no orphans were expected.
   at NuGetGallery.DeleteAccountService.<RemovePackageOwnership>d__19.MoveNext() in E:\A\_work\172\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Services\DeleteAccountService.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetGallery.DeleteAccountService.<DeleteAccountImplAsync>d__14.MoveNext() in E:\A\_work\172\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Services\DeleteAccountService.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGetGallery.DeleteAccountService.<RunAccountDeletionTask>d__28.MoveNext() in E:\A\_work\172\s\src\Gallery\submodules\Gallery\src\NuGetGallery\Services\DeleteAccountService.cs:line 319
```

This happened on DEV environment.

**Comment by scottbommarito** [comment]
I think this is specifically because the only member of the org is the same as the only remaining owner of the package.

See https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Services/DeleteAccountService.cs#L186 and https://github.com/NuGet/NuGetGallery/blob/73a5c54629056b25b3a59960373e8fef88abff36/src/NuGetGallery/Services/PackageService.cs#L302

This logic should be made smarter.
