### ISSUE TITLE
Response status code does not indicate success: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by RukaiYu** [NuGet/NuGetGallery#6890]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe
NuGet version (x.x.x.xxx):
4.9.2.5706
dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):
windows 10 1803
Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. I followed the Nuget document to publish the package, I've created the API keys, and it starts to PUT the package to https://www.nuget.org/api/v2/package/, my package is about 169MB.

2. After some time, it shows:
InternalServerError https://www.nuget.org/api/v2/package/ 602383ms, I don't get any detailed error information.

![image](https://user-images.githubusercontent.com/3942409/52620006-44005280-2ede-11e9-8aa5-d9740af10602.png)

----- Logs
Error while copying content to a stream.
  Unable to read data from the transport connection: The connection was closed.
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferWrittenCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServerWarningLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.StsAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSourceAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpRetryHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()

-----

Are there anyone help?
Thanks!

**Comment by joelverhagen** [comment]
@RukaiYu it looks like your request is taking more than 10 minutes. It looks like we may have a problem where if a request takes more than 10 minutes, it is terminated. Could you run Fiddler and determine the response body when using nuget.exe push? My expectation is that is some JSON error message but I want to be sure.

Also, could you provide a precise timestamp of when you start the `nuget.exe push` and when it fails? 

Perhaps your internet connection or some part of the networking infrastructure between you and nuget.org is limiting the bandwidth of your upload causing it to take so long. Do you have another internet connection that you can try the push from, as a short-term workaround?

**Comment by joelverhagen** [comment]
Hey @RukaiYu, I haven't heard back from you in a week so I am going to close this issue. 

Please feel free to re-open the issue if you are still blocked.

**Comment by Friendwork** [comment]
I have same problem when trying push package to nuget

**Comment by mohitmehral** [comment]
Hy @RukaiYu  and @joelverhagen . I am facing the same issue. How you guys fix this please help me out for sometime if possible.

**Comment by joelverhagen** [comment]
Hello @Friendwork and @mohitmehral, sorry about the delay.

Could you provide the following information?

- Time, date and timezone that you encountered the area
- The package ID and version that you pushed
- Version of nuget.exe / .NET CLI that you used
- Copy-pasted output that you see from the command-line tool

**Comment by joelverhagen** [comment]
I am closing this issue for now. Please feel free to open a new issue if you are still running into this issue. To help us debug the issue, could you provide the following information in the future?

- Time, date and timezone that you encountered the area
- The package ID and version that you pushed
- Version of nuget.exe / .NET CLI that you used
- Copy-pasted output that you see from the command-line tool

**Comment by mohitmehral** [comment]
Please close I am resolved this
