### ISSUE TITLE
API Keys page returns 500 if user has too many packages

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/NuGetGallery#7032]
Tried to go to the API keys page on DEV as `NuGetTestAccount` and the page failed to load.

The offending line is [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Views/Users/ApiKeys.cshtml#L468). `Model.ApiKeys` scales with the number of packages and API keys a user has, and it seems that if the user has too many, the length of the JSON exceeds the maximum JSON length that `JavaScriptSerializer` supports and it throws an exception.

```
System.InvalidOperationException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, StringBuilder output, SerializationFormat serializationFormat)
   at System.Web.Script.Serialization.JavaScriptSerializer.Serialize(Object obj, SerializationFormat serializationFormat)
   at System.Web.Helpers.Json.Encode(Object value)
   at ASP._Page_Views_Users_ApiKeys_cshtml.<Execute>b__19() in f:\sitesroot\0\Views\Users\ApiKeys.cshtml:line 466
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass7.<RenderSection>b__5(TextWriter tw)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at ASP._Page_Views_Shared_gallery_Layout_cshtml.Execute() in f:\sitesroot\0\Views\Shared\Gallery\Layout.cshtml:line 48
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by scottbommarito** [comment]
My `JsonConvert` mitigation seems to have resolved the 500 response issue, but now the client-side JavaScript times out and then crashes on Chrome. Unfortunately, I expect improving the client-side to be a large task, but this mitigation has at least improved the situation.

**Comment by scottbommarito** [comment]
Not sure if `NuGetTestAccount` saw `500`s before on the API keys page on INT and PROD, but it doesn't right now.
