### ISSUE TITLE
[Azure Search] Db2AzureSearch job throws exception for tokens

### ISSUE THREAD

**Issue by shishirx34** [NuGet/NuGetGallery#7045]
Bug during building index:

```
2019-04-04 13:11:12 [Error] An exception was thrown while sending documents to index "hijack-001".
Microsoft.Azure.Search.IndexBatchException: 1 of 1000 indexing actions in the batch failed. The remaining actions succeeded and modified the index. Check the IndexResponse property for the status of each index action.
   at Microsoft.Azure.Search.DocumentsOperations.<DoIndexWithHttpMessagesAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Search.DocumentsOperationsExtensions.<IndexAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.AzureSearch.Wrappers.DocumentsOperationsWrapper.<IndexAsync>d__2`1.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\Wrappers\DocumentsOperationsWrapper.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.AzureSearch.BatchPusher.<IndexAsync>d__15.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 208
2019-04-04 13:11:12 [Error] Indexing document with key "codeforcelib_utilities_2_0_0-Y29kZWZvcmNlbGliLnV0aWxpdGllcy8yLjAuMA2" failed for index "hijack-001". 400: "A custom analyzer must not produce tokens longer than 300 characters. To trim them or ignore them use the TruncateTokenFilter and the LengthTokenFilter respectively."
2019-04-04 13:11:12 [Error] 1 errors were found when indexing a batch for index "hijack-001". 1 were logged.
2019-04-04 13:11:12 [Error] An exception was thrown while processing package ID "Codaxy.Dextop.Core".
System.InvalidOperationException: Errors were found when indexing a batch. Up to 5 errors get logged. ---> Microsoft.Azure.Search.IndexBatchException: 1 of 1000 indexing actions in the batch failed. The remaining actions succeeded and modified the index. Check the IndexResponse property for the status of each index action.
   at Microsoft.Azure.Search.DocumentsOperations.<DoIndexWithHttpMessagesAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Search.DocumentsOperationsExtensions.<IndexAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.AzureSearch.Wrappers.DocumentsOperationsWrapper.<IndexAsync>d__2`1.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\Wrappers\DocumentsOperationsWrapper.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.AzureSearch.BatchPusher.<IndexAsync>d__15.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 208
   --- End of inner exception stack trace ---
   at NuGet.Services.AzureSearch.BatchPusher.<IndexAsync>d__15.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.AzureSearch.BatchPusher.<PushBatchesAsync>d__14.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.AzureSearch.BatchPusher.<PushBatchesAsync>d__13.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.AzureSearch.BatchPusher.<PushFullBatchesAsync>d__11.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.AzureSearch.Db2AzureSearch.Db2AzureSearchCommand.<ConsumeWorkAsync>d__14.MoveNext() in E:\Nuget\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\Db2AzureSearch\Db2AzureSearchCommand.cs:line 172

```

**Comment by shishirx34** [comment]
Using `TokenFilterName.Truncate` on Description custom analyzer seems to be working fine for executing the job. However, this means that the tokens will be truncate the token lenght down to max of 300 chars

**Comment by shishirx34** [comment]
along with the Truncate, we need to update the tokenizer with whitespace splits.
