### ISSUE TITLE
catalog2registration becomes very slow when there is too much parallelism

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7101]
See these lines:
https://github.com/NuGet/NuGet.Services.Metadata/blob/5039a75e8ef636f1a9b69b83f2751bb429903b61/src/Catalog/Registration/RegistrationPersistence.cs#L133-L146

For packages with many versions, this can result in many parallel HTTP requests.

Consider these two:

momentum.pm.portalapi - 103 pages
momentum.pm.api - 92 pages

If these two IDs are processed in parallel, there will be over 200 parallel HTTP requests. We saw catalog2registration hang indefinitely when these two package IDs (and some smaller ones) were done in parallel:

```
traces
| where timestamp > todatetime('2019-04-25T13:00:00.000')
| where customDimensions.InstanceName == "catalog2registration-global"
| extend pid = tostring(customDimensions.ProcessId)
| summarize sum(itemCount) by bin(timestamp, 1m), strcat(pid, " ", iff(severityLevel >= 2, "error", "okay"))
| render timechart 
```

![image](https://user-images.githubusercontent.com/94054/56755558-a67a9800-6744-11e9-8a62-b980c9d7cb9d.png)

The red is before the issue -- this process crashed due to a seemingly transient storage issue. The green, blue and purple are with default batch parallelism. As you can see it gets stuck.

The violet/lilac process is when we reduce the `-maxConcurrentBatch` to 1. It moves forward happily at this point because the two `momentum.pm.*` packages are not done in parallel, presumably.

An easy fix here is have a global (static/singleton) semaphore around the page download operation so that not too many downloads occur. This semaphore for be of a constant size, e.g. 32 or use `-maxConcurrentBatches`.

**Comment by joelverhagen** [comment]
The loading is actually twice as bad as I thought. We do SemVer 1.0.0 and SemVer 2.0.0 is parallel.

**Comment by joelverhagen** [comment]
From perfmon locally. A LOT of time is being spent in GC, leading up to an OutOfMemoryException.
![image](https://user-images.githubusercontent.com/94054/56994584-55a7dc80-6b54-11e9-8206-27b5e5751eed.png)

**Comment by joelverhagen** [comment]
Stack of the OOM:
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at VDS.RDF.Query.Algebra.Multiset.get_Variables()
   at VDS.RDF.Query.Algebra.BaseMultiset.<>c__DisplayClassa.<LeftJoin>b__7(String v)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VDS.RDF.Query.Algebra.BaseMultiset.LeftJoin(BaseMultiset other, ISparqlExpression expr)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.Algebra.LeftJoin.Evaluate(SparqlEvaluationContext context)
   at VDS.RDF.Query.SparqlEvaluationContext.Evaluate(ISparqlAlgebra algebra)
   at VDS.RDF.Query.LeviathanQueryProcessor.ProcessQuery(IRdfHandler rdfHandler, ISparqlResultsHandler resultsHandler, SparqlQuery query)
   at VDS.RDF.Query.LeviathanQueryProcessor.ProcessQuery(SparqlQuery query)
   at NuGet.Services.Metadata.Catalog.Helpers.SparqlHelpers.Execute(TripleStore store, String sparql) in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Helpers\SparqlHelpers.cs:line 28
   at NuGet.Services.Metadata.Catalog.Helpers.SparqlHelpers.Construct(TripleStore store, String sparql) in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Helpers\SparqlHelpers.cs:line 14
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationPersistence.AddExistingItem(IDictionary`2 resources, TripleStore store, Uri catalogEntry) in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationPersistence.cs:line 107
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationPersistence.GetResources(IGraph graph) in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationPersistence.cs:line 75
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationPersistence.<Load>d__10.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationPersistence.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationMaker.<ProcessAsync>d__1.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationMaker.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationCollector.<ProcessGraphsAsync>d__18.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationCollector.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.Metadata.Catalog.SortingGraphCollector.<ProcessSortedBatchAsync>d__2.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\SortingGraphCollector.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at NuGet.Services.Metadata.Catalog.SortingCollector`1.<OnProcessBatchAsync>d__1.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\SortingCollector.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Services.Metadata.Catalog.Registration.RegistrationCollector.<ProcessBatchAsync>d__20.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Services.Metadata\src\Catalog\Registration\RegistrationCollector.cs:line 208
```

**Comment by joelverhagen** [comment]
The process is 32-bit. Easiest thing will probably be to move to a 64-bit process.
