### ISSUE TITLE
[Azure Search] Db2AzureSearch gets throttled

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#7109]
Running `db2azuresearch` on an Azure Search index with "Standard" size and 1 partition will hit throttling limits:

>  503: "Failed to execute indexing request for this document because not enough resources were available. You may be reaching the limits of your provisioned capacity. Please try again later or adjust the number of replicas. See http://aka.ms/azure-search-throttling for more information."

This can be circumvented by lowering the `Db2AzureSearch:MaxConcurrentBatches` configuration to slow down the tool. We should consider the following after performance testing our final implementation:

* Decrease the `Db2AzureSearch:MaxConcurrentBatches` configuration to slow down ingestion
* Increase the Azure Search partition count to increases our write throughput capacity

Stack trace on throttling:

```
System.InvalidOperationException: Errors were found when indexing a batch. Up to 5 errors get logged. ---> Microsoft.Azure.Search.IndexBatchException: 503 of 1000 indexing actions in the batch failed. The remaining actions succeeded and modified the index. Check the IndexResponse property for the status of each index action.
   
at Microsoft.Azure.Search.DocumentsOperations.<DoIndexWithHttpMessagesAsync>d__23.MoveNext()
at Microsoft.Azure.Search.DocumentsOperationsExtensions.<IndexAsync>d__13`1.MoveNext()
at NuGet.Services.AzureSearch.Wrappers.DocumentsOperationsWrapper.<IndexAsync>d__2`1.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\Wrappers\DocumentsOperationsWrapper.cs:line 22
at NuGet.Services.AzureSearch.BatchPusher.<IndexAsync>d__15.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 208
at NuGet.Services.AzureSearch.BatchPusher.<IndexAsync>d__15.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 274
at NuGet.Services.AzureSearch.BatchPusher.<PushBatchesAsync>d__14.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 129
at NuGet.Services.AzureSearch.BatchPusher.<PushBatchesAsync>d__13.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 102
at NuGet.Services.AzureSearch.BatchPusher.<PushFullBatchesAsync>d__11.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\BatchPusher.cs:line 92
at NuGet.Services.AzureSearch.Db2AzureSearch.Db2AzureSearchCommand.<ConsumeWorkAsync>d__14.MoveNext() in E:\NuGet.Services.Metadata\src\NuGet.Services.AzureSearch\Db2AzureSearch\Db2AzureSearchCommand.cs:line 172
```

**Comment by joelverhagen** [comment]
We've obtained sufficient throughput in PROD with 4 concurrent batches and 8 version list writers. These levels of concurrency avoid throttling and should be used until we have a reason to change them.
