### ISSUE TITLE
Nuget.Server replies 406 on push request if .nuspec contains <group targetFramework="...">

### ISSUE THREAD

**Issue by MadKoder** [NuGet/NuGetGallery#7665]
When the server is running on a computer with different profiles in "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable", if the .nuspec has group dependencies with targetFrameworkl, the push fails.

Build and run a server with Nuget.Server v3.4.1 package, on a computed that contains different profiles in "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable".
Push a package that contains for exemple 
\<dependencies\>
      \<group targetFramework="netstandard2.0" /\>
\</dependencies\>
The server replies with 406 (Not acceptable)

After a thorough inspection, I could find the source of the problem, in the deprecated package Nuget.Core:
When the nuspec contains a group with a targetFramework attribute, the method NuGet.Server.Core.FrameworkNameExtensions.ToShortNameOrNull() is called. and after that, down the call stack, there is a "new NetPortableProfile" with parameter "supportedFrameworks" given an empty enumerable.
This triggers the throw of an ArgumentOutOfRangeException, and seems to be the cause of the 406 reply.

Why the IEnumerable supportedFrameworks is empty ? Because it is filled by a code that scans "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable". Going down the directories, this code reads xml files found in "vXXX\Profile\ProfileYYY\SupportedFrameworks" subdirectories.
For each "ProfileYYY" directory, it construct a NetPortableProfile, and the supportedFrameworks is filled by these xml files.
BUT, I don't know why, profiles that starts with "Mono" or "Xamarin" are considered optionals, and removed from the list. Problem is that, on my computer, there are only Xamarin and Mono profiles...

To find this, I had to use the project Core found in Nuget.Client sources, and replaced in Nuget.Server sources the dependency to the deprecated package by this project. After that, if I add a test to check if the IEnumerable is not empty before trying to construct a NetPortableProfile, everything seems to be working fine.
Of course this is a terrible hack, but for me the fundamental problem is that Nuget.Server use a deprecated package with no official sources, so there was no other way for me to find a solution.

So, did anybody already encountered this problem ? Is Something wrong in my computer configuration (the supported frameworks) ?

Thanks for your support!

**Comment by maratoss** [comment]
Have the same problem, here is NugetServer log:
```
Info: Start adding package AnyClone 1.1.0.
Info: Start rebuilding package store...
Info: Start reading packages from disk...
Info: Finished reading packages from disk.
Info: Start adding packages from drop folder.
Info: Finished adding packages from drop folder.
Info: Finished rebuilding package store.
w3wp.exe Error: 0 : System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: supportedFrameworks
   at NuGet.NetPortableProfile..ctor(String version, String name, IEnumerable`1 supportedFrameworks, IEnumerable`1 optionalFrameworks)
   at NuGet.NetPortableProfileTable.LoadPortableProfile(String version, String profileName, IFileSystem fileSystem, IEnumerable`1 frameworkFiles)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items)
   at NuGet.NetPortableProfileTable.BuildPortableProfileCollection()
   at NuGet.NetPortableProfileTable.get_Instance()
   at NuGet.Server.Core.FrameworkNameExtensions.ToShortNameOrNull(FrameworkName current)
   at NuGet.Server.Core.Infrastructure.ServerPackage.DependencySetsAsString(IEnumerable`1 dependencySets)
   at NuGet.Server.Core.Infrastructure.ServerPackage..ctor(IPackage package, PackageDerivedData packageDerivedData)
   at NuGet.Server.Core.Infrastructure.ServerPackageStore.Add(IPackage package, Boolean enableDelisting)
   at NuGet.Server.Core.Infrastructure.ServerPackageRepository.<AddPackageAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Server.V2.Controllers.NuGetODataController.<UploadPackage>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

```

**Comment by loic-sharma** [comment]
Sadly, I haven't been able to root-cause this yet. We believe that the contents in `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable` are filled by installing Visual Studio. We believe that installing older versions of Visual Studio, like Visual Studio 2017 or Visual Studio 2015, **may** fix your issue. Could you try that and let us know?

In the meantime, we'll keep digging on our end!

**Comment by MadKoder** [comment]
Hello, and thanks for your work. Yes, I agree that the problem may be solved by installing VS17, if I remember well, it appeared when I desinstalled VS 17. But I can't use this option because I need nuget server on an integration computer that must validate compilation with VS 19 only, and I don't wan't to be polluted by another VS version installed. But it's OK, for the moment I think I will use my corrected version.
As I said in my first message, the source of the problem is clear : the deprecated package Nuget.Core, that contains buggy code. I don't think VS 19 is at fault here.
So if you wan't to solve this, the only solution I see is to replace this package by its sources, like it's done for Nuget.Client, and correct these sources.
So it's up to you to decide if you wan't to make this move.
Again, thanks for your support.
