### ISSUE TITLE
Unit test "RunInternal_WithMultipleDeletedPackagesWithSamePackageIdentity_PutsEachPackageInSeparateCommit" is flaky

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#7743]
This is in NuGet.Services.Metadata:
https://github.com/NuGet/NuGet.Services.Metadata/blob/bc7b6b5f3f84728946785d2021487876b130eb24/tests/NgTests/Db2CatalogTests.cs#L533

```
##[error]    NgTests.Db2CatalogTests.RunInternal_WithMultipleDeletedPackagesWithSamePackageIdentity_PutsEachPackageInSeparateCommit [FAIL]

      Assert.Equal() Failure
      Expected: 5
      Actual:   3
      Stack Trace:
        tests\NgTests\Db2CatalogTests.cs(1345,0): at NgTests.Db2CatalogTests.VerifyCatalog(Nullable`1 expectedLastCreated, Nullable`1 expectedLastDeleted, Nullable`1 expectedLastEdited, PackageOperation skippedOperation)
        tests\NgTests\Db2CatalogTests.cs(1288,0): at NgTests.Db2CatalogTests.<RunInternalAndVerifyAsync>d__52.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        tests\NgTests\Db2CatalogTests.cs(558,0): at NgTests.Db2CatalogTests.<RunInternal_WithMultipleDeletedPackagesWithSamePackageIdentity_PutsEachPackageInSeparateCommit>d__35.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Output:
        Information: CATALOG LastCreated: 0001-01-01T00:00:00.0000000Z
        Information: DATABASE CreatedPackages: 1
        Information: Creating package catalog item for JYDztRwlslJv9T8e 2.9.4
        Information: Finished creating package catalog item for JYDztRwlslJv9T8e 2.9.4
        Information: Add metadata from: https://unittest.org/packages/jydztrwlsljv9t8e/2.9.4.nupkg
        Information: COMMIT metadata to catalog.
        Information: CATALOG LastEdited: 0001-01-01T00:00:00.0000000Z
        Information: DATABASE EditedPackages: 0
        Information: CATALOG LastDeleted: 2019-12-06T01:26:18.5511052Z
        Information: FEED DeletedPackages: 0
        Information: CATALOG LastCreated: 2019-12-06T01:26:18.5511052Z
        Information: DATABASE CreatedPackages: 0
        Information: CATALOG LastEdited: 0001-01-01T00:00:00.0000000Z
        Information: DATABASE EditedPackages: 0
        Information: CATALOG LastDeleted: 2019-12-06T01:26:18.5511052Z
        Information: FEED DeletedPackages: 0
        Information: CATALOG LastCreated: 2019-12-06T01:26:18.5511052Z
        Information: DATABASE CreatedPackages: 0
        Information: CATALOG LastEdited: 0001-01-01T00:00:00.0000000Z
        Information: DATABASE EditedPackages: 0

```
See build:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299584&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=22

**Comment by xavierdecoster** [comment]
No idea why, but this happened again. Build: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=68451&view=logs&j=92a4755a-6173-591e-5c07-8dbe1165e937&t=637fe98e-01bc-52d5-2c1e-725d000dcfda&l=22
