### ISSUE TITLE
upload pack faild to NuGet.Server 

### ISSUE THREAD

**Issue by try3** [NuGet/NuGetGallery#7955]
1、NuGet.Server 3.4.1
2、if file name contain chinese in package (2 file names of the same length
) ,server it will response 406
===
exception:
![Snipaste_2020-04-20_15-58-20](https://user-images.githubusercontent.com/17698581/79738344-33900700-832f-11ea-9f12-f4189731245f.png)

Cannot correctly extract the file name containing Chinese char

**Comment by joelverhagen** [comment]
Could you provide a package that reproduces the problem? You can either post it here or, if you are concerned about privacy, you could send a file sharing link (like Google Drive, Dropbox, OneDrive) of the package to support@nuget.org.

**Comment by try3** [comment]
[TestPack.1.0.0.zip](https://github.com/NuGet/NuGetGallery/files/4507870/TestPack.1.0.0.zip)

this is a test pack can reproduce bugs

**Comment by joelverhagen** [comment]
Thanks for the repro. I have narrowed down the issue to a couple points:

1. When NuGet 4.6.0 creates a package with Chinese characters in the file name, it no longer encodes the file names.
1. Non-encoded file names with Chinese characters cause System.IO.Packaging to throw an exception on .NET Framework.

The full exception text, as you mentioned, is here:
```
iisexpress.exe Error: 0 : System.ArgumentException: Item has already been added. Key in dictionary: 'contentFiles/any/any/modules/testpack/wwwroot/????????????.txt'  Key being added: 'contentFiles/any/any/modules/testpack/wwwroot/????????????.txt'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.ParseRecord(BinaryReader reader, Int64 centralDirectoryOffset, Int32 centralDirectoryCount, Int64 expectedCentralDirectorySize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipIOBlockManager.get_CentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at NuGet.PackageHelper.GetManifestStream(Stream packageStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath, IFileSystem expandedFileSystem)
   at NuGet.Server.Core.PackageFactory.Open(String fullPackagePath) in D:\src\git\github.com\NuGet\NuGet.Server\src\NuGet.Server.Core\Core\PackageFactory.cs:line 23
   at NuGet.Server.V2.Controllers.NuGetODataController.<UploadPackage>d__16.MoveNext() in D:\src\git\github.com\NuGet\NuGet.Server\src\NuGet.Server.V2\Controllers\NuGetODataController.cs:line 401
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

I have opened a bug on the NuGet client side regarding this change in encoding: https://github.com/NuGet/Home/issues/9459

I was able to workaround this issue by creating the package using [nuget.exe 4.5.3](https://dist.nuget.org/win-x86-commandline/v4.5.3/nuget.exe).

**Comment by try3** [comment]
thanks
