### ISSUE TITLE
[Heartbeats noise] Durable cursor sometimes fails due to storage timeout

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/NuGetGallery#8062]
### Describe the bug

Catalog2Registration should have retries on Blob Storage. This exception was logged:

```
"Job Failed to Run": "Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndExecuteAsync[T](IAsyncResult result) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 51
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.<CreateCallbackVoid>b__5(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.Persistence.AzureStorage.<OnLoadAsync>d__19.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\Persistence\AzureStorage.cs:line 356
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.Persistence.Storage.<LoadAsync>d__17.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\Persistence\Storage.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.Persistence.Storage.<LoadStringAsync>d__19.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\Persistence\Storage.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.DurableCursor.<LoadAsync>d__5.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\DurableCursor.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Catalog2Registration.Catalog2RegistrationCommand.<ExecuteAsync>d__9.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Catalog2RegistrationCommand.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Catalog2Registration.Catalog2RegistrationCommand.<ExecuteAsync>d__8.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Catalog2RegistrationCommand.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Job.<Run>d__1.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Job.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<JobLoop>d__14.MoveNext() in E:\A\_work\3286\s\src\NuGet.Jobs.Common\JobRunner.cs:line 265
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:
"
```

### To Reproduce

See if you can put a delegating handler in the request pipeline.
Add a host name mapping for the Azure Blob Storage to 192.168.255.255. 

### Expected behavior

There should be retries. It's not clear that there are retries implemented in the code. Let's verify retries occur for exceptions like these.

**Comment by joelverhagen** [comment]
Looks like there ARE retries.
![image](https://user-images.githubusercontent.com/94054/85084603-2e620380-b18a-11ea-832d-acbe6eaddd56.png)

However the server timeout used to be 60 seconds for legacy Catalog2Registration.
https://nuget.visualstudio.com/NuGetMicrosoft/_git/NuGetDeployment/commit/c65b5357495a88be156275434988d67dcf8ed04c?path=%2Fsrc%2FJobs%2FNuGet.Jobs.Cloud%2FJobs%2FCatalog2Registration%2FDEV%2Feastasia%2Freg4%2FRunJob.cmd

We are using 10 minutes for Catalog2Dnx (which is the default):
https://github.com/NuGet/NuGet.Services.Metadata/blob/590468b93894e4580684b42735d7287ecf5f49c3/src/Ng/CommandHelpers.cs#L209

**Comment by joelverhagen** [comment]
Looks like there were two exceptions actually.

First (job failed after 44.149 seconds, occurred in the `HttpClient` based `HttpReadCursor`)
`
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.72.64.10:443
`
<details>
<pre>
"Job Failed to Run": "System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.72.64.10:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.TelemetryHandler.<SendAsync>d__2.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\Telemetry\TelemetryHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.HttpReadCursor.<LoadAsync>d__5.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\HttpReadCursor.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.AggregateCursor.<LoadAsync>d__5.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\AggregateCursor.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Services.Metadata.Catalog.CollectorBase.<RunAsync>d__10.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\Catalog\CollectorBase.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Catalog2Registration.Catalog2RegistrationCommand.<ExecuteAsync>d__9.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Catalog2RegistrationCommand.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Catalog2Registration.Catalog2RegistrationCommand.<ExecuteAsync>d__8.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Catalog2RegistrationCommand.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.Job.<Run>d__1.MoveNext() in C:\A\vs2017mb-00000R-1\_work\3\s\src\NuGet.Jobs.Catalog2Registration\Job.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<JobLoop>d__14.MoveNext() in E:\A\_work\3286\s\src\NuGet.Jobs.Common\JobRunner.cs:line 265"
</pre>
</details>

Second (job failed after 601.043 seconds, in the Azure Storage SDK-based `DurableCursor`):
`Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.`

(full exception above)

Definitely looks like a legitimate network issue. USNC (which runs Catalog2Dnx for China) had no problem at that time... which is strange...

**Comment by joelverhagen** [comment]
This same problem (similar stack as original) happens periodically in Catalog2AzureSearch.
