### ISSUE TITLE
Dependency Injection broken on GitHubVulnerabilities2Db

### ISSUE THREAD

**Issue by drewgillies** [NuGet/NuGetGallery#8138]
This change: https://github.com/NuGet/NuGetGallery/pull/8112, specifically [here](https://github.com/NuGet/NuGetGallery/pull/8112/files#diff-b744cb446049fcb4c87628c3d31a964fR39) has introduced a new parameter into the PackageService constructor, breaking dependency injection in GitHubVulnerabilities2Db.

Salient part of exception:
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:\r\nCannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 
**'Void .ctor(
NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], 
NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], 
NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], 
NuGetGallery.Auditing.IAuditingService, 
NuGetGallery.ITelemetryService, 
NuGetGallery.Security.ISecurityPolicyService, 
NuGetGallery.IEntitiesContext, 
NuGetGallery.IContentObjectService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)"}**

Full trace:
Job Failed to Run: Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AdvisoryCollector (ReflectionActivator), Services = [GitHubVulnerabilities2Db.Collector.IAdvisoryCollector], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AdvisoryIngestor (ReflectionActivator), Services = [GitHubVulnerabilities2Db.Ingest.IAdvisoryIngestor], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageVulnerabilityService (ReflectionActivator), Services = [NuGetGallery.IPackageVulnerabilityService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageUpdateService (ReflectionActivator), Services = [NuGetGallery.IPackageUpdateService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageService (ReflectionActivator), Services = [NuGetGallery.IPackageService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = AdvisoryIngestor (ReflectionActivator), Services = [GitHubVulnerabilities2Db.Ingest.IAdvisoryIngestor], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageVulnerabilityService (ReflectionActivator), Services = [NuGetGallery.IPackageVulnerabilityService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageUpdateService (ReflectionActivator), Services = [NuGetGallery.IPackageUpdateService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageService (ReflectionActivator), Services = [NuGetGallery.IPackageService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageVulnerabilityService (ReflectionActivator), Services = [NuGetGallery.IPackageVulnerabilityService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageUpdateService (ReflectionActivator), Services = [NuGetGallery.IPackageUpdateService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageService (ReflectionActivator), Services = [NuGetGallery.IPackageService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageUpdateService (ReflectionActivator), Services = [NuGetGallery.IPackageUpdateService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageService (ReflectionActivator), Services = [NuGetGallery.IPackageService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = PackageService (ReflectionActivator), Services = [NuGetGallery.IPackageService], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'. (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'NuGetGallery.PackageService' can be invoked with the available services and parameters:
Cannot resolve parameter 'NuGetGallery.IContentObjectService contentObjectService' of constructor 'Void .ctor(NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.PackageRegistration], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Package], NuGetGallery.IEntityRepository`1[NuGet.Services.Entities.Certificate], NuGetGallery.Auditing.IAuditingService, NuGetGallery.ITelemetryService, NuGetGallery.Security.ISecurityPolicyService, NuGetGallery.IEntitiesContext, NuGetGallery.IContentObjectService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 160
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 115
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 133
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 82
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 168
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\AutowiringParameter.cs:line 57
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ConstructorParameterBinding.cs:line 116
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 115
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 133
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 82
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 168
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\AutowiringParameter.cs:line 57
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ConstructorParameterBinding.cs:line 116
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 115
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 133
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 82
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 168
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\AutowiringParameter.cs:line 57
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ConstructorParameterBinding.cs:line 116
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 115
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 133
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 82
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 168
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass0_0.<CanSupplyValue>b__0() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\AutowiringParameter.cs:line 57
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ConstructorParameterBinding.cs:line 116
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Activators\Reflection\ReflectionActivator.cs:line 120
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 115
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 133
   at Autofac.Core.Resolving.InstanceLookup.Execute() in C:\projects\autofac\src\Autofac\Core\Resolving\InstanceLookup.cs:line 82
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 130
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Resolving\ResolveOperation.cs:line 92
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Lifetime\LifetimeScope.cs:line 276
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\Core\Container.cs:line 170
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in C:\projects\autofac\src\Autofac\ResolutionExtensions.cs:line 1041
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in C:\projects\autofac\src\Autofac\ResolutionExtensions.cs:line 871
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType) in C:\projects\autofac-extensions-dependencyinjection\src\Autofac.Extensions.DependencyInjection\AutofacServiceProvider.cs:line 71
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at GitHubVulnerabilities2Db.Job.<Run>d__1.MoveNext() in C:\Repos\NuGetGallery\src\GitHubVulnerabilities2Db\Job.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Jobs.JobRunner.<JobLoop>d__14.MoveNext() in E:\A\_work\4806\s\src\NuGet.Jobs.Common\JobRunner.cs:line 263

**Comment by drewgillies** [comment]
@joelverhagen My work here is to figure out the appropriate use of this type for GitHubVulnerabilities2Db purposes. Hints welcome. :)
