### ISSUE TITLE
[NuGet.org Bug]: NuGet Restore encountering intermittent Timeout/SSL/TLS issue

### ISSUE THREAD

**Issue by lavareas** [NuGet/NuGetGallery#9103]
### Impact

I'm unable to use NuGet.org

### Describe the bug

Currently while trying to restore NuGet packages, the project requires both internal business NuGets as well as agi.nuget.org nugets.

While building we are attempting to restore, and it attempts api.nuget.org first.  Normally we would expect 404s for NuGets not there, but existing inside of our Local Network.

Intermittently instead of getting the expected 404 response, we are seeing 

An error occurred while sending the request.
  The underlying connection was closed: An unexpected error occurred on a send.
  Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

The StackTrace itself from ADO pipelines shows 

NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information about 'xxxxxxxxxx' from remote source 'https://api.nuget.org/v3-flatcontainer/xxxxxxxxxx/index.json'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.ServerWarningLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.StsAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Protocol.HttpSourceAuthenticationHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass2_1.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.TimeoutUtility.<StartWithTimeout>d__0`1.MoveNext()

We have tested this also by calling the URL via Postman, and would regularly see failed calls due to timeouts.  We have tried this both on and off of our company VPN so as to rule out our own internal systems.

### Repro Steps

Call any api.nuget.org/v3-flatcontainer/*/index.json that you expect to not be there.

Could take multiple attempts to fail as this is an intermittent, but regular  issue.

Should see a 404 exception message without the call failing in Azure DevOps Pipelines.

### Expected Behavior

Expecting non-relevant nugets to return 404 as expected, then fall into searching the next repo without breaking active directory build tasks.

**Comment by agr** [comment]
First, please consider using [package source mapping](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.0#source-mapping) to nail packages to specific sources for you projects.

Second, please check the cipher suites available on your build machines against the list specified in the following announcement: https://github.com/NuGet/Announcements/issues/60. And feel free to reach out to the support email with details about your location, OS used for build machines, TLS details and what `api.nuget.org` resolves to when it fails.

**Comment by deNoor** [comment]
I also got this issue `The SSL connection could not be established, see inner exception.` + `An existing connection was forcibly closed by the remote host` on Windows Server 2012R2.
It has been working for many years but somehow broke today.

@lavareas 
To fix check the suggested [announcement](https://github.com/NuGet/Announcements/issues/60) or the api.nuget.org [certificate](https://www.ssllabs.com/ssltest/analyze.html?d=api.nuget.org&s=2620%3a1ec%3a46%3a0%3a0%3a0%3a0%3a69&hideResults=on) directly.
Make sure that TLS 1.2 is enabled in your system,
and at least one of the Cipher suites is enabled. (scroll down the report to see this block).

For me all both TLS_ECDHE_RSA_* were absent and both TLS_DHE_RSA_* were disabled.

**Comment by lavareas** [comment]
> First, please consider using [package source mapping](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.0#source-mapping) to nail packages to specific sources for you projects.
> 
> Second, please check the cipher suites available on your build machines against the list specified in the following announcement: [NuGet/Announcements#60](https://github.com/NuGet/Announcements/issues/60). And feel free to reach out to the support email with details about your location, OS used for build machines, TLS details and what `api.nuget.org` resolves to when it fails.

Thanks for the quick reply yesterday.

Currently we are using NuGet 5.11, which currently does not support Source Mapping.  What kind of options might we have for 5.11?

For context, we currently do not use NuGet.Config files, and are a C# 8.0+ Project stack.  Normally we just use the Right Click NuGetPackage Manager interface of Visual Studio 2019.

**Comment by joelverhagen** [comment]
Package source mapping will eliminate unnecessary HTTP requests to package sources that aren't expected to have specific packages. This is very useful in a situation where you have multiple package sources (e.g. some private packages on AzDO, some public packages on NuGet.org). If you're using a build pipeline, it's theoretically possible to use a newer version of .NET SDK on your build pipeline compared to locally on your dev machines. In general, this can work most times because newer versions of the SDK can build projects targeting older frameworks.

Regarding the connection between the client (sounds like both your local dev environment and your build agents) and NuGet.org, could you provide the following troubleshooting information and send it to support@nuget.org?
https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-download-packages-from-or-upload-packages-to-nuget-org

This will allow our support team to help you diagnose connectivity issues.

**Comment by lavareas** [comment]
Heya @joelverhagen 

I can confirm we are not seeing the connectivity issues this morning, it appears they stopped sometime last night around 11pm CST.  We believe it may be related to a CDN issue at Edgecast that was going on most of the day yesterday.

Absolutely agreed that Package Source Mapping is a great idea, but part of the Problem is we have DotNetCore applications, which do not allow the NuGet.config files, and instead forces usaged of PackReferences inside of the C# .csproj file itself.

Digging around the NuGet/Microsoft document, it appears that PackReferences don't have the required pieces to do Package Source Mapping?  Am I mistaken here?

If this is the case, what would be some other available options for this specific scenario?  Right now we are in a 'future mitigation' stage.  We are looking at local proxy servers for NuGet packages incase NuGet.Org is unavailable, and also looking for available routes to minimize calling NuGet.org with expected 404 responses :)

Appreciate any knowledge you can share!

**Comment by lavareas** [comment]
Thanks for the quick engagement @joelverhagen , your rocking today!

> If you are comfortable, could you mention what country your package downloads are running from? We have multiple CDNs used by NuGet.org that vary in priority based on geography. Currently, all of US uses Microsoft CDN, Europe uses a mix of Edgecast (Verizon CDN) and Microsoft CDN, and the rest of the world uses Verizon CDN.

Ideally we would hope we are using the Microsoft CDN, however we learned yesterday that in some instances we are routing to Europe!  We caught this on a GeoLocation security item yesterday, where a call to NuGet was going to a GeoLocation blocked territory for some reason.  Is there some way we can configure NuGet to force it to go through the Microsoft CDN to stay stateside?

> The <PackageReference> type of dependency does indeed support package source mapping! In fact, we hope that most users leverage both <PackageReference> and package source mapping in concert 😃 for all of their projects. Could you provide links to placed where the documentation is confusing? This seems like a great find on your part, and it would be great for us to tidy things up so it's less confusing.

>For an example, here is the NuGet.config for NuGetGallery (the project that backs [www.nuget.org](http://www.nuget.org/), which leverages <PackageReference>):
https://github.com/NuGet/NuGetGallery/blob/main/NuGet.config

>Alternatively, you can open an issue on our docs repo: https://github.com/NuGet/docs.microsoft.com-nuget describing how the applicability of package source mapping is confusing from a docs perspective.

I think the confusion here is we have been told outright that DotNetCore Applications flat cannot use NuGet.Config files in their application stacks due to it being unsupported by those application types.  That being said, can the PackageSource Mapping line items be added straight to the .csproj file itself?  The application your referencing looks like a .Net Framework 4.7.2 application which would allow the NuGet.Config files.

> I would be curious to see how package upstreaming works for you in Azure DevOps.
https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops

>This would make your NuGet client software go to one feed (Azure Artifacts) and internally this feed would reach out to NuGet.org. This could be one mitigation worth trying next time you run into trouble.

This is actually one of the items we were just discussing in house.  However it appears it is also leaning into NuGet.Config.

I think the major catch item at the moment we are stuck on is the NuGet.Config/Microsoft.NETCore.App support item?  Is this just something we are fundamentally misunderstanding?

**Comment by lavareas** [comment]
Just occurred to me I misunderstood something on the CDN standpoint.  It is very likely the Dev was using a NuGet that was published from a different country.  This would cause it to use that countries CDN I presume?

**Comment by joelverhagen** [comment]
> Ideally we would hope we are using the Microsoft CDN, however we learned yesterday that in some instances we are routing to Europe! We caught this on a GeoLocation security item yesterday, where a call to NuGet was going to a GeoLocation blocked territory for some reason. Is there some way we can configure NuGet to force it to go through the Microsoft CDN to stay stateside?

We don't support that today, no. The hypothesis that we're acting under is that during "normal" times, the pick we make between CDNs on behalf of the user in a specific geo is the right one.

Since the routing is done at a DNS level, we don't have as many levers to cleverly route traffic of `api.nuget.org` requests based on client settings. It may be possible for users to cobble something together with a custom DNS resolver where the `api.nuget.org` CNAME chain (or some specific CNAME records) are fixed to something, but it would be an undocumented and unsupported flow at this point.

In short, our team really wants the CDN provider to be an invisible implementation detail. If we have undetected availability issues with specific CDN providers, that just means we need to improve our monitoring, reporting, or failover strategies.

Over the next month, we will be completing our Microsoft CDN rollout and all of Europe will be using Microsoft CDN as the primary. Perhaps this is enough to mitigate the problem for you specifically.

> I think the confusion here is we have been told outright that DotNetCore Applications flat cannot use NuGet.Config files in their application stacks due to it being unsupported by those application types.

Okay, now I'm **really** confused 😄. When I see "DotNetCore applications" I think applications based on the .NET SDK 2.1, 3.1, 5.0, 6.0 etc. These project types certainly support NuGet.config. NuGet.config sets repository, solution, or user level settings like package sources, credentials, etc ([docs](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)).

The thing that is not supported in .NET Core cases is _packages.config_. Perhaps there was a miscommunication in the past related to this similar name? Packages.config is the "old" way to represent dependencies per project which we have since moved away from in lieu of `<PackageReference>` in the .csproj. Packages.config is still the default for legacy .NET Framework projects but .NET Core and .NET (5+) projects should be using `<PackageReference>`.

See here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#project-type-support.

> Just occurred to me I misunderstood something on the CDN standpoint. It is very likely the Dev was using a NuGet that was published from a different country. This would cause it to use that countries CDN I presume?

Where a package is published **from** ("ingress") is not a relevant detail for the consumption ("egress") side. A package published to NuGet.org from any part of the world becomes available globally.

**Comment by lavareas** [comment]
>Okay, now I'm really confused 😄. When I see "DotNetCore applications" I think applications based on the .NET SDK 2.1, 3.1, 5.0, 6.0 etc. These project types certainly support NuGet.config. NuGet.config sets repository, solution, or user level settings like package sources, credentials, etc ([docs](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)).

>The thing that is not supported in .NET Core cases is packages.config. Perhaps there was a miscommunication in the past related to this similar name? Packages.config is the "old" way to represent dependencies per project which we have since moved away from in lieu of <PackageReference> in the .csproj. Packages.config is still the default for legacy .NET Framework projects but .NET Core and .NET (5+) projects should be using <PackageReference>.

>See here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#project-type-support.

Lol!  The link is what we are doing today.   We are a .NET 5.0 Project.  I think your very correct here, I think their was very likely a communication issue somewhere 'waaaay' in ancient history confusing Packages.config with NuGet.config now that I am getting deeper into this.

I'll have one of the projects give putting in a NuGet.config and shot and see how it pans out.  I'll respond in a day or so and let you know how it goes :)

**Comment by sergiomcalzada** [comment]
Same issue here since Friday 29

Windows server 2012 R2
Cipher suits checked and enabled.
TLS 1.2 enabled

nslookup api.nuget.org
```
Non-authoritative answer:
Name:    part-0032.t-0009.t-msedge.net
Addresses:  2620:1ec:46::60
          2620:1ec:bdf::60
          13.107.213.60
          13.107.246.60
Aliases:  api.nuget.org
          nugetapiprod.trafficmanager.net
          apiprod-mscdn.azureedge.net
          apiprod-mscdn.afd.azureedge.net
          star-azureedge-prod.trafficmanager.net
          dual.part-0032.t-0009.t-msedge.net
```

Also checked: works in chrome but not in internet explorer.

**Comment by zhhyu** [comment]
Hello, @sergiomcalzada! 

For Windows server 2012 R2, please ensure that any of the following two cipher suites have been enabled on the machine:
```
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
```
There needs an exact matched cipher suite to build the connection.

It will be helpful to check Schannel SSP:
https://docs.microsoft.com/en-us/windows-server/security/tls/manage-tls#configuring-tls-cipher-suite-order-by-using-group-policy
and also TLS/cipher suites related registry keys:
https://docs.microsoft.com/en-us/windows-server/security/tls/tls-registry-settings

It’s possible that your organization places a policy to block using those cipher suites.

Feel free to reach out to the support mailbox if you need the further assistance: https://www.nuget.org/policies/Contact

**Comment by joelverhagen** [comment]
There has been no activity on this issue for more than a week. If you are still facing connectivity issues with api.nuget.org, please check the recommendations here:
https://github.com/NuGet/NuGetGallery/issues/9103#issuecomment-1104391820
https://github.com/NuGet/NuGetGallery/issues/9103#issuecomment-1117740061

If you are still facing any issue, please feel free to contact us (https://www.nuget.org/policies/Contact, please log in for the contact form) or opening an issue in this repository.
